"""Monolith5 — compiled, proven-equivalent runtime implementation.

Mechanically generated by ``tools/compile_monolith5.py`` from the exact,
exhaustively verified ``tools/monolith5_gate_model.json`` and
``tools/monolith5_model.json`` formula (see MONOLITH5_ANALYSIS.md). This
is the same per-bit formula as the interpreter in
``tools/monolith5_gate_model.py``, unrolled into straight-line code to
remove interpretation overhead — no new cryptanalysis. DO NOT EDIT —
regenerate with ``python -m tools.compile_monolith5 --write``.

This module is the runtime implementation used by
``monolith_wrappers.py``. ``family0/_generated/monolith5.py``
(HarpoS7-derived, MIT-licensed; see ``LICENSE-HarpoS7``) is kept only
for provenance/audit and is no longer called here — a proven,
byte-for-byte equivalent representation change per issue #1's
acceptance criteria, not a behavior change. It is also about 1.6x
smaller and about 2.2x faster than the generated implementation and
needs no runtime JSON loading; see MODEL_BENCHMARKS.md.
"""

from __future__ import annotations

import struct
from collections.abc import Sequence

_U32 = 0xFFFFFFFF


def execute_words(source: Sequence[int]) -> tuple[int, ...]:
    """Map 54 source words to twelve destination words."""
    if len(source) < 54:
        raise ValueError("Monolith5 requires at least 54 source words")

    L0_0 = (
        (
            (source[1] ^ ((source[0] ^ source[1]) & source[2]))
            | (source[19] ^ ((source[18] ^ source[19]) & source[20]))
            | (source[37] ^ ((source[36] ^ source[37]) & source[38]))
        )
        ^ (
            (source[1] ^ ((source[0] ^ source[1]) & source[2]))
            & (source[19] ^ ((source[18] ^ source[19]) & source[20]))
            & (source[37] ^ ((source[36] ^ source[37]) & source[38]))
        )
    ) & _U32
    L0_1 = (
        (((source[2] ^ _U32) & source[0]) ^ ((source[2] ^ _U32) & source[1]) ^ (source[0] & source[1]))
        ^ (((source[20] ^ _U32) & source[18]) ^ ((source[20] ^ _U32) & source[19]) ^ (source[18] & source[19]))
        ^ (((source[38] ^ _U32) & source[36]) ^ ((source[38] ^ _U32) & source[37]) ^ (source[36] & source[37]))
    ) & _U32
    L0_2 = (
        (source[1] ^ ((source[0] ^ source[1]) & source[2]))
        | (source[19] ^ ((source[18] ^ source[19]) & source[20]))
        | (source[37] ^ ((source[36] ^ source[37]) & source[38]))
    ) & _U32
    L0_3 = (
        (
            (((source[2] ^ _U32) & source[0]) ^ ((source[2] ^ _U32) & source[1]) ^ (source[0] & source[1]))
            & (((source[20] ^ _U32) & source[18]) ^ ((source[20] ^ _U32) & source[19]) ^ (source[18] & source[19]))
        )
        ^ (
            (((source[2] ^ _U32) & source[0]) ^ ((source[2] ^ _U32) & source[1]) ^ (source[0] & source[1]))
            & (((source[38] ^ _U32) & source[36]) ^ ((source[38] ^ _U32) & source[37]) ^ (source[36] & source[37]))
        )
        ^ (
            (((source[20] ^ _U32) & source[18]) ^ ((source[20] ^ _U32) & source[19]) ^ (source[18] & source[19]))
            & (((source[38] ^ _U32) & source[36]) ^ ((source[38] ^ _U32) & source[37]) ^ (source[36] & source[37]))
        )
    ) & _U32
    L0_4 = (
        (source[1] ^ ((source[2] ^ source[1]) & source[0]))
        ^ (source[19] ^ ((source[20] ^ source[19]) & source[18]))
        ^ (source[37] ^ ((source[38] ^ source[37]) & source[36]))
    ) & _U32
    L0_5 = (
        ((source[1] ^ ((source[2] ^ source[1]) & source[0])) & (source[19] ^ ((source[20] ^ source[19]) & source[18])))
        ^ ((source[1] ^ ((source[2] ^ source[1]) & source[0])) & (source[37] ^ ((source[38] ^ source[37]) & source[36])))
        ^ ((source[19] ^ ((source[20] ^ source[19]) & source[18])) & (source[37] ^ ((source[38] ^ source[37]) & source[36])))
    ) & _U32
    L0_6 = (
        (source[0] ^ (((source[1] ^ _U32) ^ source[0]) & source[2]))
        ^ (source[18] ^ (((source[19] ^ _U32) ^ source[18]) & source[20]))
        ^ (source[36] ^ (((source[37] ^ _U32) ^ source[36]) & source[38]))
    ) & _U32
    L0_7 = (
        (source[1] ^ ((source[0] ^ source[1]) & source[2]))
        ^ (source[19] ^ ((source[18] ^ source[19]) & source[20]))
        ^ (source[37] ^ ((source[36] ^ source[37]) & source[38]))
    ) & _U32
    L0_8 = (
        (
            (source[0] ^ (((source[1] ^ _U32) ^ source[0]) & source[2]))
            & (source[18] ^ (((source[19] ^ _U32) ^ source[18]) & source[20]))
        )
        ^ (
            (source[0] ^ (((source[1] ^ _U32) ^ source[0]) & source[2]))
            & (source[36] ^ (((source[37] ^ _U32) ^ source[36]) & source[38]))
        )
        ^ (
            (source[18] ^ (((source[19] ^ _U32) ^ source[18]) & source[20]))
            & (source[36] ^ (((source[37] ^ _U32) ^ source[36]) & source[38]))
        )
    ) & _U32
    L0_9 = (
        (source[0] ^ ((source[2] ^ source[0]) & source[1]))
        ^ (source[18] ^ ((source[20] ^ source[18]) & source[19]))
        ^ (source[36] ^ ((source[38] ^ source[36]) & source[37]))
    ) & _U32
    L0_10 = (
        ((source[0] ^ ((source[2] ^ source[0]) & source[1])) & (source[18] ^ ((source[20] ^ source[18]) & source[19])))
        ^ ((source[0] ^ ((source[2] ^ source[0]) & source[1])) & (source[36] ^ ((source[38] ^ source[36]) & source[37])))
        ^ ((source[18] ^ ((source[20] ^ source[18]) & source[19])) & (source[36] ^ ((source[38] ^ source[36]) & source[37])))
    ) & _U32
    L0_11 = (
        (source[1] ^ (((source[2] ^ _U32) ^ source[1]) & source[0]))
        ^ (source[19] ^ (((source[20] ^ _U32) ^ source[19]) & source[18]))
        ^ (source[37] ^ (((source[38] ^ _U32) ^ source[37]) & source[36]))
    ) & _U32
    L0_12 = (
        (
            (source[1] ^ (((source[2] ^ _U32) ^ source[1]) & source[0]))
            & (source[19] ^ (((source[20] ^ _U32) ^ source[19]) & source[18]))
        )
        ^ (
            (source[1] ^ (((source[2] ^ _U32) ^ source[1]) & source[0]))
            & (source[37] ^ (((source[38] ^ _U32) ^ source[37]) & source[36]))
        )
        ^ (
            (source[19] ^ (((source[20] ^ _U32) ^ source[19]) & source[18]))
            & (source[37] ^ (((source[38] ^ _U32) ^ source[37]) & source[36]))
        )
    ) & _U32
    L0_13 = (
        (source[0] ^ (((source[2] ^ _U32) ^ source[0]) & source[1]))
        ^ (source[18] ^ (((source[20] ^ _U32) ^ source[18]) & source[19]))
        ^ (source[36] ^ (((source[38] ^ _U32) ^ source[36]) & source[37]))
    ) & _U32
    L0_14 = (
        (
            (source[0] ^ (((source[2] ^ _U32) ^ source[0]) & source[1]))
            & (source[18] ^ (((source[20] ^ _U32) ^ source[18]) & source[19]))
        )
        ^ (
            (source[0] ^ (((source[2] ^ _U32) ^ source[0]) & source[1]))
            & (source[36] ^ (((source[38] ^ _U32) ^ source[36]) & source[37]))
        )
        ^ (
            (source[18] ^ (((source[20] ^ _U32) ^ source[18]) & source[19]))
            & (source[36] ^ (((source[38] ^ _U32) ^ source[36]) & source[37]))
        )
    ) & _U32
    L0_15 = (
        (source[2] ^ ((source[0] ^ source[2]) & source[1]))
        ^ (source[20] ^ ((source[18] ^ source[20]) & source[19]))
        ^ (source[38] ^ ((source[36] ^ source[38]) & source[37]))
    ) & _U32
    L0_16 = (
        ((source[2] ^ ((source[0] ^ source[2]) & source[1])) & (source[20] ^ ((source[18] ^ source[20]) & source[19])))
        ^ ((source[2] ^ ((source[0] ^ source[2]) & source[1])) & (source[38] ^ ((source[36] ^ source[38]) & source[37])))
        ^ ((source[20] ^ ((source[18] ^ source[20]) & source[19])) & (source[38] ^ ((source[36] ^ source[38]) & source[37])))
    ) & _U32
    L0_17 = (
        ((source[0] & source[1]) ^ (source[0] & source[2]) ^ (source[1] & source[2]))
        ^ ((source[18] & source[19]) ^ (source[18] & source[20]) ^ (source[19] & source[20]))
        ^ ((source[36] & source[37]) ^ (source[36] & source[38]) ^ (source[37] & source[38]))
    ) & _U32
    L0_18 = (
        (
            ((source[0] & source[1]) ^ (source[0] & source[2]) ^ (source[1] & source[2]))
            & ((source[18] & source[19]) ^ (source[18] & source[20]) ^ (source[19] & source[20]))
        )
        ^ (
            ((source[0] & source[1]) ^ (source[0] & source[2]) ^ (source[1] & source[2]))
            & ((source[36] & source[37]) ^ (source[36] & source[38]) ^ (source[37] & source[38]))
        )
        ^ (
            ((source[18] & source[19]) ^ (source[18] & source[20]) ^ (source[19] & source[20]))
            & ((source[36] & source[37]) ^ (source[36] & source[38]) ^ (source[37] & source[38]))
        )
    ) & _U32
    L0_19 = (
        (source[2] ^ (((source[0] ^ _U32) ^ source[2]) & source[1]))
        ^ (source[20] ^ (((source[18] ^ _U32) ^ source[20]) & source[19]))
        ^ (source[38] ^ (((source[36] ^ _U32) ^ source[38]) & source[37]))
    ) & _U32
    L0_20 = (
        (
            (source[2] ^ (((source[0] ^ _U32) ^ source[2]) & source[1]))
            & (source[20] ^ (((source[18] ^ _U32) ^ source[20]) & source[19]))
        )
        ^ (
            (source[2] ^ (((source[0] ^ _U32) ^ source[2]) & source[1]))
            & (source[38] ^ (((source[36] ^ _U32) ^ source[38]) & source[37]))
        )
        ^ (
            (source[20] ^ (((source[18] ^ _U32) ^ source[20]) & source[19]))
            & (source[38] ^ (((source[36] ^ _U32) ^ source[38]) & source[37]))
        )
    ) & _U32
    L0_21 = (
        (source[0] ^ ((source[1] ^ source[0]) & source[2]))
        ^ (source[18] ^ ((source[19] ^ source[18]) & source[20]))
        ^ (source[36] ^ ((source[37] ^ source[36]) & source[38]))
    ) & _U32
    L0_22 = (
        ((source[0] ^ ((source[1] ^ source[0]) & source[2])) & (source[18] ^ ((source[19] ^ source[18]) & source[20])))
        ^ ((source[0] ^ ((source[1] ^ source[0]) & source[2])) & (source[36] ^ ((source[37] ^ source[36]) & source[38])))
        ^ ((source[18] ^ ((source[19] ^ source[18]) & source[20])) & (source[36] ^ ((source[37] ^ source[36]) & source[38])))
    ) & _U32
    L0_23 = (
        (source[1] ^ (((source[0] ^ _U32) ^ source[1]) & source[2]))
        ^ (source[19] ^ (((source[18] ^ _U32) ^ source[19]) & source[20]))
        ^ (source[37] ^ (((source[36] ^ _U32) ^ source[37]) & source[38]))
    ) & _U32
    L0_24 = (
        (
            (source[1] ^ (((source[0] ^ _U32) ^ source[1]) & source[2]))
            & (source[19] ^ (((source[18] ^ _U32) ^ source[19]) & source[20]))
        )
        ^ (
            (source[1] ^ (((source[0] ^ _U32) ^ source[1]) & source[2]))
            & (source[37] ^ (((source[36] ^ _U32) ^ source[37]) & source[38]))
        )
        ^ (
            (source[19] ^ (((source[18] ^ _U32) ^ source[19]) & source[20]))
            & (source[37] ^ (((source[36] ^ _U32) ^ source[37]) & source[38]))
        )
    ) & _U32
    L0_25 = (
        (source[2] ^ ((source[1] ^ source[2]) & source[0]))
        ^ (source[20] ^ ((source[19] ^ source[20]) & source[18]))
        ^ (source[38] ^ ((source[37] ^ source[38]) & source[36]))
    ) & _U32
    L0_26 = (
        ((source[2] ^ ((source[1] ^ source[2]) & source[0])) & (source[20] ^ ((source[19] ^ source[20]) & source[18])))
        ^ ((source[2] ^ ((source[1] ^ source[2]) & source[0])) & (source[38] ^ ((source[37] ^ source[38]) & source[36])))
        ^ ((source[20] ^ ((source[19] ^ source[20]) & source[18])) & (source[38] ^ ((source[37] ^ source[38]) & source[36])))
    ) & _U32
    L0_27 = (
        ((source[1] ^ ((source[0] ^ source[1]) & source[2])) & (source[19] ^ ((source[18] ^ source[19]) & source[20])))
        ^ ((source[1] ^ ((source[0] ^ source[1]) & source[2])) & (source[37] ^ ((source[36] ^ source[37]) & source[38])))
        ^ ((source[19] ^ ((source[18] ^ source[19]) & source[20])) & (source[37] ^ ((source[36] ^ source[37]) & source[38])))
    ) & _U32
    L0_28 = (
        (((source[0] ^ _U32) & source[1]) ^ ((source[0] ^ _U32) & source[2]) ^ (source[1] & source[2]))
        ^ (((source[18] ^ _U32) & source[19]) ^ ((source[18] ^ _U32) & source[20]) ^ (source[19] & source[20]))
        ^ (((source[36] ^ _U32) & source[37]) ^ ((source[36] ^ _U32) & source[38]) ^ (source[37] & source[38]))
    ) & _U32
    L0_29 = (
        (
            (((source[0] ^ _U32) & source[1]) ^ ((source[0] ^ _U32) & source[2]) ^ (source[1] & source[2]))
            & (((source[18] ^ _U32) & source[19]) ^ ((source[18] ^ _U32) & source[20]) ^ (source[19] & source[20]))
        )
        ^ (
            (((source[0] ^ _U32) & source[1]) ^ ((source[0] ^ _U32) & source[2]) ^ (source[1] & source[2]))
            & (((source[36] ^ _U32) & source[37]) ^ ((source[36] ^ _U32) & source[38]) ^ (source[37] & source[38]))
        )
        ^ (
            (((source[18] ^ _U32) & source[19]) ^ ((source[18] ^ _U32) & source[20]) ^ (source[19] & source[20]))
            & (((source[36] ^ _U32) & source[37]) ^ ((source[36] ^ _U32) & source[38]) ^ (source[37] & source[38]))
        )
    ) & _U32
    L0_30 = (
        (((source[1] ^ _U32) & source[0]) ^ ((source[1] ^ _U32) & source[2]) ^ (source[0] & source[2]))
        ^ (((source[19] ^ _U32) & source[18]) ^ ((source[19] ^ _U32) & source[20]) ^ (source[18] & source[20]))
        ^ (((source[37] ^ _U32) & source[36]) ^ ((source[37] ^ _U32) & source[38]) ^ (source[36] & source[38]))
    ) & _U32
    L0_31 = (
        (
            (((source[1] ^ _U32) & source[0]) ^ ((source[1] ^ _U32) & source[2]) ^ (source[0] & source[2]))
            & (((source[19] ^ _U32) & source[18]) ^ ((source[19] ^ _U32) & source[20]) ^ (source[18] & source[20]))
        )
        ^ (
            (((source[1] ^ _U32) & source[0]) ^ ((source[1] ^ _U32) & source[2]) ^ (source[0] & source[2]))
            & (((source[37] ^ _U32) & source[36]) ^ ((source[37] ^ _U32) & source[38]) ^ (source[36] & source[38]))
        )
        ^ (
            (((source[19] ^ _U32) & source[18]) ^ ((source[19] ^ _U32) & source[20]) ^ (source[18] & source[20]))
            & (((source[37] ^ _U32) & source[36]) ^ ((source[37] ^ _U32) & source[38]) ^ (source[36] & source[38]))
        )
    ) & _U32
    L1_1 = (
        (((source[5] ^ _U32) & source[3]) ^ ((source[5] ^ _U32) & source[4]) ^ (source[3] & source[4]))
        ^ (((source[23] ^ _U32) & source[21]) ^ ((source[23] ^ _U32) & source[22]) ^ (source[21] & source[22]))
        ^ (((source[41] ^ _U32) & source[39]) ^ ((source[41] ^ _U32) & source[40]) ^ (source[39] & source[40]))
    ) & _U32
    L1_3 = (
        (
            (((source[5] ^ _U32) & source[3]) ^ ((source[5] ^ _U32) & source[4]) ^ (source[3] & source[4]))
            & (((source[23] ^ _U32) & source[21]) ^ ((source[23] ^ _U32) & source[22]) ^ (source[21] & source[22]))
        )
        ^ (
            (((source[5] ^ _U32) & source[3]) ^ ((source[5] ^ _U32) & source[4]) ^ (source[3] & source[4]))
            & (((source[41] ^ _U32) & source[39]) ^ ((source[41] ^ _U32) & source[40]) ^ (source[39] & source[40]))
        )
        ^ (
            (((source[23] ^ _U32) & source[21]) ^ ((source[23] ^ _U32) & source[22]) ^ (source[21] & source[22]))
            & (((source[41] ^ _U32) & source[39]) ^ ((source[41] ^ _U32) & source[40]) ^ (source[39] & source[40]))
        )
    ) & _U32
    L1_4 = (
        (source[4] ^ ((source[5] ^ source[4]) & source[3]))
        ^ (source[22] ^ ((source[23] ^ source[22]) & source[21]))
        ^ (source[40] ^ ((source[41] ^ source[40]) & source[39]))
    ) & _U32
    L1_5 = (
        ((source[4] ^ ((source[5] ^ source[4]) & source[3])) & (source[22] ^ ((source[23] ^ source[22]) & source[21])))
        ^ ((source[4] ^ ((source[5] ^ source[4]) & source[3])) & (source[40] ^ ((source[41] ^ source[40]) & source[39])))
        ^ ((source[22] ^ ((source[23] ^ source[22]) & source[21])) & (source[40] ^ ((source[41] ^ source[40]) & source[39])))
    ) & _U32
    L1_6 = (
        (source[3] ^ (((source[4] ^ _U32) ^ source[3]) & source[5]))
        ^ (source[21] ^ (((source[22] ^ _U32) ^ source[21]) & source[23]))
        ^ (source[39] ^ (((source[40] ^ _U32) ^ source[39]) & source[41]))
    ) & _U32
    L1_8 = (
        (
            (source[3] ^ (((source[4] ^ _U32) ^ source[3]) & source[5]))
            & (source[21] ^ (((source[22] ^ _U32) ^ source[21]) & source[23]))
        )
        ^ (
            (source[3] ^ (((source[4] ^ _U32) ^ source[3]) & source[5]))
            & (source[39] ^ (((source[40] ^ _U32) ^ source[39]) & source[41]))
        )
        ^ (
            (source[21] ^ (((source[22] ^ _U32) ^ source[21]) & source[23]))
            & (source[39] ^ (((source[40] ^ _U32) ^ source[39]) & source[41]))
        )
    ) & _U32
    L1_9 = (
        (source[3] ^ ((source[5] ^ source[3]) & source[4]))
        ^ (source[21] ^ ((source[23] ^ source[21]) & source[22]))
        ^ (source[39] ^ ((source[41] ^ source[39]) & source[40]))
    ) & _U32
    L1_10 = (
        ((source[3] ^ ((source[5] ^ source[3]) & source[4])) & (source[21] ^ ((source[23] ^ source[21]) & source[22])))
        ^ ((source[3] ^ ((source[5] ^ source[3]) & source[4])) & (source[39] ^ ((source[41] ^ source[39]) & source[40])))
        ^ ((source[21] ^ ((source[23] ^ source[21]) & source[22])) & (source[39] ^ ((source[41] ^ source[39]) & source[40])))
    ) & _U32
    L1_11 = (
        (source[4] ^ (((source[5] ^ _U32) ^ source[4]) & source[3]))
        ^ (source[22] ^ (((source[23] ^ _U32) ^ source[22]) & source[21]))
        ^ (source[40] ^ (((source[41] ^ _U32) ^ source[40]) & source[39]))
    ) & _U32
    L1_12 = (
        (
            (source[4] ^ (((source[5] ^ _U32) ^ source[4]) & source[3]))
            & (source[22] ^ (((source[23] ^ _U32) ^ source[22]) & source[21]))
        )
        ^ (
            (source[4] ^ (((source[5] ^ _U32) ^ source[4]) & source[3]))
            & (source[40] ^ (((source[41] ^ _U32) ^ source[40]) & source[39]))
        )
        ^ (
            (source[22] ^ (((source[23] ^ _U32) ^ source[22]) & source[21]))
            & (source[40] ^ (((source[41] ^ _U32) ^ source[40]) & source[39]))
        )
    ) & _U32
    L1_13 = (
        (source[3] ^ (((source[5] ^ _U32) ^ source[3]) & source[4]))
        ^ (source[21] ^ (((source[23] ^ _U32) ^ source[21]) & source[22]))
        ^ (source[39] ^ (((source[41] ^ _U32) ^ source[39]) & source[40]))
    ) & _U32
    L1_14 = (
        (
            (source[3] ^ (((source[5] ^ _U32) ^ source[3]) & source[4]))
            & (source[21] ^ (((source[23] ^ _U32) ^ source[21]) & source[22]))
        )
        ^ (
            (source[3] ^ (((source[5] ^ _U32) ^ source[3]) & source[4]))
            & (source[39] ^ (((source[41] ^ _U32) ^ source[39]) & source[40]))
        )
        ^ (
            (source[21] ^ (((source[23] ^ _U32) ^ source[21]) & source[22]))
            & (source[39] ^ (((source[41] ^ _U32) ^ source[39]) & source[40]))
        )
    ) & _U32
    L1_15 = (
        (source[5] ^ ((source[3] ^ source[5]) & source[4]))
        ^ (source[23] ^ ((source[21] ^ source[23]) & source[22]))
        ^ (source[41] ^ ((source[39] ^ source[41]) & source[40]))
    ) & _U32
    L1_16 = (
        ((source[5] ^ ((source[3] ^ source[5]) & source[4])) & (source[23] ^ ((source[21] ^ source[23]) & source[22])))
        ^ ((source[5] ^ ((source[3] ^ source[5]) & source[4])) & (source[41] ^ ((source[39] ^ source[41]) & source[40])))
        ^ ((source[23] ^ ((source[21] ^ source[23]) & source[22])) & (source[41] ^ ((source[39] ^ source[41]) & source[40])))
    ) & _U32
    L1_17 = (
        ((source[3] & source[4]) ^ (source[3] & source[5]) ^ (source[4] & source[5]))
        ^ ((source[21] & source[22]) ^ (source[21] & source[23]) ^ (source[22] & source[23]))
        ^ ((source[39] & source[40]) ^ (source[39] & source[41]) ^ (source[40] & source[41]))
    ) & _U32
    L1_18 = (
        (
            ((source[3] & source[4]) ^ (source[3] & source[5]) ^ (source[4] & source[5]))
            & ((source[21] & source[22]) ^ (source[21] & source[23]) ^ (source[22] & source[23]))
        )
        ^ (
            ((source[3] & source[4]) ^ (source[3] & source[5]) ^ (source[4] & source[5]))
            & ((source[39] & source[40]) ^ (source[39] & source[41]) ^ (source[40] & source[41]))
        )
        ^ (
            ((source[21] & source[22]) ^ (source[21] & source[23]) ^ (source[22] & source[23]))
            & ((source[39] & source[40]) ^ (source[39] & source[41]) ^ (source[40] & source[41]))
        )
    ) & _U32
    L1_19 = (
        (source[5] ^ (((source[3] ^ _U32) ^ source[5]) & source[4]))
        ^ (source[23] ^ (((source[21] ^ _U32) ^ source[23]) & source[22]))
        ^ (source[41] ^ (((source[39] ^ _U32) ^ source[41]) & source[40]))
    ) & _U32
    L1_20 = (
        (
            (source[5] ^ (((source[3] ^ _U32) ^ source[5]) & source[4]))
            & (source[23] ^ (((source[21] ^ _U32) ^ source[23]) & source[22]))
        )
        ^ (
            (source[5] ^ (((source[3] ^ _U32) ^ source[5]) & source[4]))
            & (source[41] ^ (((source[39] ^ _U32) ^ source[41]) & source[40]))
        )
        ^ (
            (source[23] ^ (((source[21] ^ _U32) ^ source[23]) & source[22]))
            & (source[41] ^ (((source[39] ^ _U32) ^ source[41]) & source[40]))
        )
    ) & _U32
    L1_21 = (
        (source[3] ^ ((source[4] ^ source[3]) & source[5]))
        ^ (source[21] ^ ((source[22] ^ source[21]) & source[23]))
        ^ (source[39] ^ ((source[40] ^ source[39]) & source[41]))
    ) & _U32
    L1_22 = (
        ((source[3] ^ ((source[4] ^ source[3]) & source[5])) & (source[21] ^ ((source[22] ^ source[21]) & source[23])))
        ^ ((source[3] ^ ((source[4] ^ source[3]) & source[5])) & (source[39] ^ ((source[40] ^ source[39]) & source[41])))
        ^ ((source[21] ^ ((source[22] ^ source[21]) & source[23])) & (source[39] ^ ((source[40] ^ source[39]) & source[41])))
    ) & _U32
    L1_25 = (
        (source[5] ^ ((source[4] ^ source[5]) & source[3]))
        ^ (source[23] ^ ((source[22] ^ source[23]) & source[21]))
        ^ (source[41] ^ ((source[40] ^ source[41]) & source[39]))
    ) & _U32
    L1_26 = (
        ((source[5] ^ ((source[4] ^ source[5]) & source[3])) & (source[23] ^ ((source[22] ^ source[23]) & source[21])))
        ^ ((source[5] ^ ((source[4] ^ source[5]) & source[3])) & (source[41] ^ ((source[40] ^ source[41]) & source[39])))
        ^ ((source[23] ^ ((source[22] ^ source[23]) & source[21])) & (source[41] ^ ((source[40] ^ source[41]) & source[39])))
    ) & _U32
    L1_28 = (
        (((source[3] ^ _U32) & source[4]) ^ ((source[3] ^ _U32) & source[5]) ^ (source[4] & source[5]))
        ^ (((source[21] ^ _U32) & source[22]) ^ ((source[21] ^ _U32) & source[23]) ^ (source[22] & source[23]))
        ^ (((source[39] ^ _U32) & source[40]) ^ ((source[39] ^ _U32) & source[41]) ^ (source[40] & source[41]))
    ) & _U32
    L1_29 = (
        (
            (((source[3] ^ _U32) & source[4]) ^ ((source[3] ^ _U32) & source[5]) ^ (source[4] & source[5]))
            & (((source[21] ^ _U32) & source[22]) ^ ((source[21] ^ _U32) & source[23]) ^ (source[22] & source[23]))
        )
        ^ (
            (((source[3] ^ _U32) & source[4]) ^ ((source[3] ^ _U32) & source[5]) ^ (source[4] & source[5]))
            & (((source[39] ^ _U32) & source[40]) ^ ((source[39] ^ _U32) & source[41]) ^ (source[40] & source[41]))
        )
        ^ (
            (((source[21] ^ _U32) & source[22]) ^ ((source[21] ^ _U32) & source[23]) ^ (source[22] & source[23]))
            & (((source[39] ^ _U32) & source[40]) ^ ((source[39] ^ _U32) & source[41]) ^ (source[40] & source[41]))
        )
    ) & _U32
    L1_30 = (
        (((source[4] ^ _U32) & source[3]) ^ ((source[4] ^ _U32) & source[5]) ^ (source[3] & source[5]))
        ^ (((source[22] ^ _U32) & source[21]) ^ ((source[22] ^ _U32) & source[23]) ^ (source[21] & source[23]))
        ^ (((source[40] ^ _U32) & source[39]) ^ ((source[40] ^ _U32) & source[41]) ^ (source[39] & source[41]))
    ) & _U32
    L1_31 = (
        (
            (((source[4] ^ _U32) & source[3]) ^ ((source[4] ^ _U32) & source[5]) ^ (source[3] & source[5]))
            & (((source[22] ^ _U32) & source[21]) ^ ((source[22] ^ _U32) & source[23]) ^ (source[21] & source[23]))
        )
        ^ (
            (((source[4] ^ _U32) & source[3]) ^ ((source[4] ^ _U32) & source[5]) ^ (source[3] & source[5]))
            & (((source[40] ^ _U32) & source[39]) ^ ((source[40] ^ _U32) & source[41]) ^ (source[39] & source[41]))
        )
        ^ (
            (((source[22] ^ _U32) & source[21]) ^ ((source[22] ^ _U32) & source[23]) ^ (source[21] & source[23]))
            & (((source[40] ^ _U32) & source[39]) ^ ((source[40] ^ _U32) & source[41]) ^ (source[39] & source[41]))
        )
    ) & _U32
    L2_1 = (
        (((source[8] ^ _U32) & source[6]) ^ ((source[8] ^ _U32) & source[7]) ^ (source[6] & source[7]))
        ^ (((source[26] ^ _U32) & source[24]) ^ ((source[26] ^ _U32) & source[25]) ^ (source[24] & source[25]))
        ^ (((source[44] ^ _U32) & source[42]) ^ ((source[44] ^ _U32) & source[43]) ^ (source[42] & source[43]))
    ) & _U32
    L2_3 = (
        (
            (((source[8] ^ _U32) & source[6]) ^ ((source[8] ^ _U32) & source[7]) ^ (source[6] & source[7]))
            & (((source[26] ^ _U32) & source[24]) ^ ((source[26] ^ _U32) & source[25]) ^ (source[24] & source[25]))
        )
        ^ (
            (((source[8] ^ _U32) & source[6]) ^ ((source[8] ^ _U32) & source[7]) ^ (source[6] & source[7]))
            & (((source[44] ^ _U32) & source[42]) ^ ((source[44] ^ _U32) & source[43]) ^ (source[42] & source[43]))
        )
        ^ (
            (((source[26] ^ _U32) & source[24]) ^ ((source[26] ^ _U32) & source[25]) ^ (source[24] & source[25]))
            & (((source[44] ^ _U32) & source[42]) ^ ((source[44] ^ _U32) & source[43]) ^ (source[42] & source[43]))
        )
    ) & _U32
    L2_6 = (
        (source[6] ^ (((source[7] ^ _U32) ^ source[6]) & source[8]))
        ^ (source[24] ^ (((source[25] ^ _U32) ^ source[24]) & source[26]))
        ^ (source[42] ^ (((source[43] ^ _U32) ^ source[42]) & source[44]))
    ) & _U32
    L2_7 = (
        (source[7] ^ ((source[6] ^ source[7]) & source[8]))
        ^ (source[25] ^ ((source[24] ^ source[25]) & source[26]))
        ^ (source[43] ^ ((source[42] ^ source[43]) & source[44]))
    ) & _U32
    L2_8 = (
        (
            (source[6] ^ (((source[7] ^ _U32) ^ source[6]) & source[8]))
            & (source[24] ^ (((source[25] ^ _U32) ^ source[24]) & source[26]))
        )
        ^ (
            (source[6] ^ (((source[7] ^ _U32) ^ source[6]) & source[8]))
            & (source[42] ^ (((source[43] ^ _U32) ^ source[42]) & source[44]))
        )
        ^ (
            (source[24] ^ (((source[25] ^ _U32) ^ source[24]) & source[26]))
            & (source[42] ^ (((source[43] ^ _U32) ^ source[42]) & source[44]))
        )
    ) & _U32
    L2_9 = (
        (source[6] ^ ((source[8] ^ source[6]) & source[7]))
        ^ (source[24] ^ ((source[26] ^ source[24]) & source[25]))
        ^ (source[42] ^ ((source[44] ^ source[42]) & source[43]))
    ) & _U32
    L2_10 = (
        ((source[6] ^ ((source[8] ^ source[6]) & source[7])) & (source[24] ^ ((source[26] ^ source[24]) & source[25])))
        ^ ((source[6] ^ ((source[8] ^ source[6]) & source[7])) & (source[42] ^ ((source[44] ^ source[42]) & source[43])))
        ^ ((source[24] ^ ((source[26] ^ source[24]) & source[25])) & (source[42] ^ ((source[44] ^ source[42]) & source[43])))
    ) & _U32
    L2_11 = (
        (source[7] ^ (((source[8] ^ _U32) ^ source[7]) & source[6]))
        ^ (source[25] ^ (((source[26] ^ _U32) ^ source[25]) & source[24]))
        ^ (source[43] ^ (((source[44] ^ _U32) ^ source[43]) & source[42]))
    ) & _U32
    L2_12 = (
        (
            (source[7] ^ (((source[8] ^ _U32) ^ source[7]) & source[6]))
            & (source[25] ^ (((source[26] ^ _U32) ^ source[25]) & source[24]))
        )
        ^ (
            (source[7] ^ (((source[8] ^ _U32) ^ source[7]) & source[6]))
            & (source[43] ^ (((source[44] ^ _U32) ^ source[43]) & source[42]))
        )
        ^ (
            (source[25] ^ (((source[26] ^ _U32) ^ source[25]) & source[24]))
            & (source[43] ^ (((source[44] ^ _U32) ^ source[43]) & source[42]))
        )
    ) & _U32
    L2_15 = (
        (source[8] ^ ((source[6] ^ source[8]) & source[7]))
        ^ (source[26] ^ ((source[24] ^ source[26]) & source[25]))
        ^ (source[44] ^ ((source[42] ^ source[44]) & source[43]))
    ) & _U32
    L2_16 = (
        ((source[8] ^ ((source[6] ^ source[8]) & source[7])) & (source[26] ^ ((source[24] ^ source[26]) & source[25])))
        ^ ((source[8] ^ ((source[6] ^ source[8]) & source[7])) & (source[44] ^ ((source[42] ^ source[44]) & source[43])))
        ^ ((source[26] ^ ((source[24] ^ source[26]) & source[25])) & (source[44] ^ ((source[42] ^ source[44]) & source[43])))
    ) & _U32
    L2_17 = (
        ((source[6] & source[7]) ^ (source[6] & source[8]) ^ (source[7] & source[8]))
        ^ ((source[24] & source[25]) ^ (source[24] & source[26]) ^ (source[25] & source[26]))
        ^ ((source[42] & source[43]) ^ (source[42] & source[44]) ^ (source[43] & source[44]))
    ) & _U32
    L2_18 = (
        (
            ((source[6] & source[7]) ^ (source[6] & source[8]) ^ (source[7] & source[8]))
            & ((source[24] & source[25]) ^ (source[24] & source[26]) ^ (source[25] & source[26]))
        )
        ^ (
            ((source[6] & source[7]) ^ (source[6] & source[8]) ^ (source[7] & source[8]))
            & ((source[42] & source[43]) ^ (source[42] & source[44]) ^ (source[43] & source[44]))
        )
        ^ (
            ((source[24] & source[25]) ^ (source[24] & source[26]) ^ (source[25] & source[26]))
            & ((source[42] & source[43]) ^ (source[42] & source[44]) ^ (source[43] & source[44]))
        )
    ) & _U32
    L2_19 = (
        (source[8] ^ (((source[6] ^ _U32) ^ source[8]) & source[7]))
        ^ (source[26] ^ (((source[24] ^ _U32) ^ source[26]) & source[25]))
        ^ (source[44] ^ (((source[42] ^ _U32) ^ source[44]) & source[43]))
    ) & _U32
    L2_20 = (
        (
            (source[8] ^ (((source[6] ^ _U32) ^ source[8]) & source[7]))
            & (source[26] ^ (((source[24] ^ _U32) ^ source[26]) & source[25]))
        )
        ^ (
            (source[8] ^ (((source[6] ^ _U32) ^ source[8]) & source[7]))
            & (source[44] ^ (((source[42] ^ _U32) ^ source[44]) & source[43]))
        )
        ^ (
            (source[26] ^ (((source[24] ^ _U32) ^ source[26]) & source[25]))
            & (source[44] ^ (((source[42] ^ _U32) ^ source[44]) & source[43]))
        )
    ) & _U32
    L2_21 = (
        (source[6] ^ ((source[7] ^ source[6]) & source[8]))
        ^ (source[24] ^ ((source[25] ^ source[24]) & source[26]))
        ^ (source[42] ^ ((source[43] ^ source[42]) & source[44]))
    ) & _U32
    L2_22 = (
        ((source[6] ^ ((source[7] ^ source[6]) & source[8])) & (source[24] ^ ((source[25] ^ source[24]) & source[26])))
        ^ ((source[6] ^ ((source[7] ^ source[6]) & source[8])) & (source[42] ^ ((source[43] ^ source[42]) & source[44])))
        ^ ((source[24] ^ ((source[25] ^ source[24]) & source[26])) & (source[42] ^ ((source[43] ^ source[42]) & source[44])))
    ) & _U32
    L2_23 = (
        (source[7] ^ (((source[6] ^ _U32) ^ source[7]) & source[8]))
        ^ (source[25] ^ (((source[24] ^ _U32) ^ source[25]) & source[26]))
        ^ (source[43] ^ (((source[42] ^ _U32) ^ source[43]) & source[44]))
    ) & _U32
    L2_24 = (
        (
            (source[7] ^ (((source[6] ^ _U32) ^ source[7]) & source[8]))
            & (source[25] ^ (((source[24] ^ _U32) ^ source[25]) & source[26]))
        )
        ^ (
            (source[7] ^ (((source[6] ^ _U32) ^ source[7]) & source[8]))
            & (source[43] ^ (((source[42] ^ _U32) ^ source[43]) & source[44]))
        )
        ^ (
            (source[25] ^ (((source[24] ^ _U32) ^ source[25]) & source[26]))
            & (source[43] ^ (((source[42] ^ _U32) ^ source[43]) & source[44]))
        )
    ) & _U32
    L2_25 = (
        (source[8] ^ ((source[7] ^ source[8]) & source[6]))
        ^ (source[26] ^ ((source[25] ^ source[26]) & source[24]))
        ^ (source[44] ^ ((source[43] ^ source[44]) & source[42]))
    ) & _U32
    L2_26 = (
        ((source[8] ^ ((source[7] ^ source[8]) & source[6])) & (source[26] ^ ((source[25] ^ source[26]) & source[24])))
        ^ ((source[8] ^ ((source[7] ^ source[8]) & source[6])) & (source[44] ^ ((source[43] ^ source[44]) & source[42])))
        ^ ((source[26] ^ ((source[25] ^ source[26]) & source[24])) & (source[44] ^ ((source[43] ^ source[44]) & source[42])))
    ) & _U32
    L2_27 = (
        ((source[7] ^ ((source[6] ^ source[7]) & source[8])) & (source[25] ^ ((source[24] ^ source[25]) & source[26])))
        ^ ((source[7] ^ ((source[6] ^ source[7]) & source[8])) & (source[43] ^ ((source[42] ^ source[43]) & source[44])))
        ^ ((source[25] ^ ((source[24] ^ source[25]) & source[26])) & (source[43] ^ ((source[42] ^ source[43]) & source[44])))
    ) & _U32
    L2_28 = (
        (((source[6] ^ _U32) & source[7]) ^ ((source[6] ^ _U32) & source[8]) ^ (source[7] & source[8]))
        ^ (((source[24] ^ _U32) & source[25]) ^ ((source[24] ^ _U32) & source[26]) ^ (source[25] & source[26]))
        ^ (((source[42] ^ _U32) & source[43]) ^ ((source[42] ^ _U32) & source[44]) ^ (source[43] & source[44]))
    ) & _U32
    L2_29 = (
        (
            (((source[6] ^ _U32) & source[7]) ^ ((source[6] ^ _U32) & source[8]) ^ (source[7] & source[8]))
            & (((source[24] ^ _U32) & source[25]) ^ ((source[24] ^ _U32) & source[26]) ^ (source[25] & source[26]))
        )
        ^ (
            (((source[6] ^ _U32) & source[7]) ^ ((source[6] ^ _U32) & source[8]) ^ (source[7] & source[8]))
            & (((source[42] ^ _U32) & source[43]) ^ ((source[42] ^ _U32) & source[44]) ^ (source[43] & source[44]))
        )
        ^ (
            (((source[24] ^ _U32) & source[25]) ^ ((source[24] ^ _U32) & source[26]) ^ (source[25] & source[26]))
            & (((source[42] ^ _U32) & source[43]) ^ ((source[42] ^ _U32) & source[44]) ^ (source[43] & source[44]))
        )
    ) & _U32
    L2_30 = (
        (((source[7] ^ _U32) & source[6]) ^ ((source[7] ^ _U32) & source[8]) ^ (source[6] & source[8]))
        ^ (((source[25] ^ _U32) & source[24]) ^ ((source[25] ^ _U32) & source[26]) ^ (source[24] & source[26]))
        ^ (((source[43] ^ _U32) & source[42]) ^ ((source[43] ^ _U32) & source[44]) ^ (source[42] & source[44]))
    ) & _U32
    L2_31 = (
        (
            (((source[7] ^ _U32) & source[6]) ^ ((source[7] ^ _U32) & source[8]) ^ (source[6] & source[8]))
            & (((source[25] ^ _U32) & source[24]) ^ ((source[25] ^ _U32) & source[26]) ^ (source[24] & source[26]))
        )
        ^ (
            (((source[7] ^ _U32) & source[6]) ^ ((source[7] ^ _U32) & source[8]) ^ (source[6] & source[8]))
            & (((source[43] ^ _U32) & source[42]) ^ ((source[43] ^ _U32) & source[44]) ^ (source[42] & source[44]))
        )
        ^ (
            (((source[25] ^ _U32) & source[24]) ^ ((source[25] ^ _U32) & source[26]) ^ (source[24] & source[26]))
            & (((source[43] ^ _U32) & source[42]) ^ ((source[43] ^ _U32) & source[44]) ^ (source[42] & source[44]))
        )
    ) & _U32
    L3_1 = (
        (((source[11] ^ _U32) & source[9]) ^ ((source[11] ^ _U32) & source[10]) ^ (source[9] & source[10]))
        ^ (((source[29] ^ _U32) & source[27]) ^ ((source[29] ^ _U32) & source[28]) ^ (source[27] & source[28]))
        ^ (((source[47] ^ _U32) & source[45]) ^ ((source[47] ^ _U32) & source[46]) ^ (source[45] & source[46]))
    ) & _U32
    L3_3 = (
        (
            (((source[11] ^ _U32) & source[9]) ^ ((source[11] ^ _U32) & source[10]) ^ (source[9] & source[10]))
            & (((source[29] ^ _U32) & source[27]) ^ ((source[29] ^ _U32) & source[28]) ^ (source[27] & source[28]))
        )
        ^ (
            (((source[11] ^ _U32) & source[9]) ^ ((source[11] ^ _U32) & source[10]) ^ (source[9] & source[10]))
            & (((source[47] ^ _U32) & source[45]) ^ ((source[47] ^ _U32) & source[46]) ^ (source[45] & source[46]))
        )
        ^ (
            (((source[29] ^ _U32) & source[27]) ^ ((source[29] ^ _U32) & source[28]) ^ (source[27] & source[28]))
            & (((source[47] ^ _U32) & source[45]) ^ ((source[47] ^ _U32) & source[46]) ^ (source[45] & source[46]))
        )
    ) & _U32
    L3_4 = (
        (source[10] ^ ((source[11] ^ source[10]) & source[9]))
        ^ (source[28] ^ ((source[29] ^ source[28]) & source[27]))
        ^ (source[46] ^ ((source[47] ^ source[46]) & source[45]))
    ) & _U32
    L3_5 = (
        ((source[10] ^ ((source[11] ^ source[10]) & source[9])) & (source[28] ^ ((source[29] ^ source[28]) & source[27])))
        ^ ((source[10] ^ ((source[11] ^ source[10]) & source[9])) & (source[46] ^ ((source[47] ^ source[46]) & source[45])))
        ^ ((source[28] ^ ((source[29] ^ source[28]) & source[27])) & (source[46] ^ ((source[47] ^ source[46]) & source[45])))
    ) & _U32
    L3_7 = (
        (source[10] ^ ((source[9] ^ source[10]) & source[11]))
        ^ (source[28] ^ ((source[27] ^ source[28]) & source[29]))
        ^ (source[46] ^ ((source[45] ^ source[46]) & source[47]))
    ) & _U32
    L3_9 = (
        (source[9] ^ ((source[11] ^ source[9]) & source[10]))
        ^ (source[27] ^ ((source[29] ^ source[27]) & source[28]))
        ^ (source[45] ^ ((source[47] ^ source[45]) & source[46]))
    ) & _U32
    L3_10 = (
        ((source[9] ^ ((source[11] ^ source[9]) & source[10])) & (source[27] ^ ((source[29] ^ source[27]) & source[28])))
        ^ ((source[9] ^ ((source[11] ^ source[9]) & source[10])) & (source[45] ^ ((source[47] ^ source[45]) & source[46])))
        ^ ((source[27] ^ ((source[29] ^ source[27]) & source[28])) & (source[45] ^ ((source[47] ^ source[45]) & source[46])))
    ) & _U32
    L3_11 = (
        (source[10] ^ (((source[11] ^ _U32) ^ source[10]) & source[9]))
        ^ (source[28] ^ (((source[29] ^ _U32) ^ source[28]) & source[27]))
        ^ (source[46] ^ (((source[47] ^ _U32) ^ source[46]) & source[45]))
    ) & _U32
    L3_12 = (
        (
            (source[10] ^ (((source[11] ^ _U32) ^ source[10]) & source[9]))
            & (source[28] ^ (((source[29] ^ _U32) ^ source[28]) & source[27]))
        )
        ^ (
            (source[10] ^ (((source[11] ^ _U32) ^ source[10]) & source[9]))
            & (source[46] ^ (((source[47] ^ _U32) ^ source[46]) & source[45]))
        )
        ^ (
            (source[28] ^ (((source[29] ^ _U32) ^ source[28]) & source[27]))
            & (source[46] ^ (((source[47] ^ _U32) ^ source[46]) & source[45]))
        )
    ) & _U32
    L3_15 = (
        (source[11] ^ ((source[9] ^ source[11]) & source[10]))
        ^ (source[29] ^ ((source[27] ^ source[29]) & source[28]))
        ^ (source[47] ^ ((source[45] ^ source[47]) & source[46]))
    ) & _U32
    L3_16 = (
        ((source[11] ^ ((source[9] ^ source[11]) & source[10])) & (source[29] ^ ((source[27] ^ source[29]) & source[28])))
        ^ ((source[11] ^ ((source[9] ^ source[11]) & source[10])) & (source[47] ^ ((source[45] ^ source[47]) & source[46])))
        ^ ((source[29] ^ ((source[27] ^ source[29]) & source[28])) & (source[47] ^ ((source[45] ^ source[47]) & source[46])))
    ) & _U32
    L3_17 = (
        ((source[9] & source[10]) ^ (source[9] & source[11]) ^ (source[10] & source[11]))
        ^ ((source[27] & source[28]) ^ (source[27] & source[29]) ^ (source[28] & source[29]))
        ^ ((source[45] & source[46]) ^ (source[45] & source[47]) ^ (source[46] & source[47]))
    ) & _U32
    L3_18 = (
        (
            ((source[9] & source[10]) ^ (source[9] & source[11]) ^ (source[10] & source[11]))
            & ((source[27] & source[28]) ^ (source[27] & source[29]) ^ (source[28] & source[29]))
        )
        ^ (
            ((source[9] & source[10]) ^ (source[9] & source[11]) ^ (source[10] & source[11]))
            & ((source[45] & source[46]) ^ (source[45] & source[47]) ^ (source[46] & source[47]))
        )
        ^ (
            ((source[27] & source[28]) ^ (source[27] & source[29]) ^ (source[28] & source[29]))
            & ((source[45] & source[46]) ^ (source[45] & source[47]) ^ (source[46] & source[47]))
        )
    ) & _U32
    L3_19 = (
        (source[11] ^ (((source[9] ^ _U32) ^ source[11]) & source[10]))
        ^ (source[29] ^ (((source[27] ^ _U32) ^ source[29]) & source[28]))
        ^ (source[47] ^ (((source[45] ^ _U32) ^ source[47]) & source[46]))
    ) & _U32
    L3_20 = (
        (
            (source[11] ^ (((source[9] ^ _U32) ^ source[11]) & source[10]))
            & (source[29] ^ (((source[27] ^ _U32) ^ source[29]) & source[28]))
        )
        ^ (
            (source[11] ^ (((source[9] ^ _U32) ^ source[11]) & source[10]))
            & (source[47] ^ (((source[45] ^ _U32) ^ source[47]) & source[46]))
        )
        ^ (
            (source[29] ^ (((source[27] ^ _U32) ^ source[29]) & source[28]))
            & (source[47] ^ (((source[45] ^ _U32) ^ source[47]) & source[46]))
        )
    ) & _U32
    L3_21 = (
        (source[9] ^ ((source[10] ^ source[9]) & source[11]))
        ^ (source[27] ^ ((source[28] ^ source[27]) & source[29]))
        ^ (source[45] ^ ((source[46] ^ source[45]) & source[47]))
    ) & _U32
    L3_22 = (
        ((source[9] ^ ((source[10] ^ source[9]) & source[11])) & (source[27] ^ ((source[28] ^ source[27]) & source[29])))
        ^ ((source[9] ^ ((source[10] ^ source[9]) & source[11])) & (source[45] ^ ((source[46] ^ source[45]) & source[47])))
        ^ ((source[27] ^ ((source[28] ^ source[27]) & source[29])) & (source[45] ^ ((source[46] ^ source[45]) & source[47])))
    ) & _U32
    L3_23 = (
        (source[10] ^ (((source[9] ^ _U32) ^ source[10]) & source[11]))
        ^ (source[28] ^ (((source[27] ^ _U32) ^ source[28]) & source[29]))
        ^ (source[46] ^ (((source[45] ^ _U32) ^ source[46]) & source[47]))
    ) & _U32
    L3_24 = (
        (
            (source[10] ^ (((source[9] ^ _U32) ^ source[10]) & source[11]))
            & (source[28] ^ (((source[27] ^ _U32) ^ source[28]) & source[29]))
        )
        ^ (
            (source[10] ^ (((source[9] ^ _U32) ^ source[10]) & source[11]))
            & (source[46] ^ (((source[45] ^ _U32) ^ source[46]) & source[47]))
        )
        ^ (
            (source[28] ^ (((source[27] ^ _U32) ^ source[28]) & source[29]))
            & (source[46] ^ (((source[45] ^ _U32) ^ source[46]) & source[47]))
        )
    ) & _U32
    L3_25 = (
        (source[11] ^ ((source[10] ^ source[11]) & source[9]))
        ^ (source[29] ^ ((source[28] ^ source[29]) & source[27]))
        ^ (source[47] ^ ((source[46] ^ source[47]) & source[45]))
    ) & _U32
    L3_26 = (
        ((source[11] ^ ((source[10] ^ source[11]) & source[9])) & (source[29] ^ ((source[28] ^ source[29]) & source[27])))
        ^ ((source[11] ^ ((source[10] ^ source[11]) & source[9])) & (source[47] ^ ((source[46] ^ source[47]) & source[45])))
        ^ ((source[29] ^ ((source[28] ^ source[29]) & source[27])) & (source[47] ^ ((source[46] ^ source[47]) & source[45])))
    ) & _U32
    L3_27 = (
        ((source[10] ^ ((source[9] ^ source[10]) & source[11])) & (source[28] ^ ((source[27] ^ source[28]) & source[29])))
        ^ ((source[10] ^ ((source[9] ^ source[10]) & source[11])) & (source[46] ^ ((source[45] ^ source[46]) & source[47])))
        ^ ((source[28] ^ ((source[27] ^ source[28]) & source[29])) & (source[46] ^ ((source[45] ^ source[46]) & source[47])))
    ) & _U32
    L3_28 = (
        (((source[9] ^ _U32) & source[10]) ^ ((source[9] ^ _U32) & source[11]) ^ (source[10] & source[11]))
        ^ (((source[27] ^ _U32) & source[28]) ^ ((source[27] ^ _U32) & source[29]) ^ (source[28] & source[29]))
        ^ (((source[45] ^ _U32) & source[46]) ^ ((source[45] ^ _U32) & source[47]) ^ (source[46] & source[47]))
    ) & _U32
    L3_29 = (
        (
            (((source[9] ^ _U32) & source[10]) ^ ((source[9] ^ _U32) & source[11]) ^ (source[10] & source[11]))
            & (((source[27] ^ _U32) & source[28]) ^ ((source[27] ^ _U32) & source[29]) ^ (source[28] & source[29]))
        )
        ^ (
            (((source[9] ^ _U32) & source[10]) ^ ((source[9] ^ _U32) & source[11]) ^ (source[10] & source[11]))
            & (((source[45] ^ _U32) & source[46]) ^ ((source[45] ^ _U32) & source[47]) ^ (source[46] & source[47]))
        )
        ^ (
            (((source[27] ^ _U32) & source[28]) ^ ((source[27] ^ _U32) & source[29]) ^ (source[28] & source[29]))
            & (((source[45] ^ _U32) & source[46]) ^ ((source[45] ^ _U32) & source[47]) ^ (source[46] & source[47]))
        )
    ) & _U32
    L3_30 = (
        (((source[10] ^ _U32) & source[9]) ^ ((source[10] ^ _U32) & source[11]) ^ (source[9] & source[11]))
        ^ (((source[28] ^ _U32) & source[27]) ^ ((source[28] ^ _U32) & source[29]) ^ (source[27] & source[29]))
        ^ (((source[46] ^ _U32) & source[45]) ^ ((source[46] ^ _U32) & source[47]) ^ (source[45] & source[47]))
    ) & _U32
    L3_31 = (
        (
            (((source[10] ^ _U32) & source[9]) ^ ((source[10] ^ _U32) & source[11]) ^ (source[9] & source[11]))
            & (((source[28] ^ _U32) & source[27]) ^ ((source[28] ^ _U32) & source[29]) ^ (source[27] & source[29]))
        )
        ^ (
            (((source[10] ^ _U32) & source[9]) ^ ((source[10] ^ _U32) & source[11]) ^ (source[9] & source[11]))
            & (((source[46] ^ _U32) & source[45]) ^ ((source[46] ^ _U32) & source[47]) ^ (source[45] & source[47]))
        )
        ^ (
            (((source[28] ^ _U32) & source[27]) ^ ((source[28] ^ _U32) & source[29]) ^ (source[27] & source[29]))
            & (((source[46] ^ _U32) & source[45]) ^ ((source[46] ^ _U32) & source[47]) ^ (source[45] & source[47]))
        )
    ) & _U32
    L4_1 = (
        (((source[14] ^ _U32) & source[12]) ^ ((source[14] ^ _U32) & source[13]) ^ (source[12] & source[13]))
        ^ (((source[32] ^ _U32) & source[30]) ^ ((source[32] ^ _U32) & source[31]) ^ (source[30] & source[31]))
        ^ (((source[50] ^ _U32) & source[48]) ^ ((source[50] ^ _U32) & source[49]) ^ (source[48] & source[49]))
    ) & _U32
    L4_3 = (
        (
            (((source[14] ^ _U32) & source[12]) ^ ((source[14] ^ _U32) & source[13]) ^ (source[12] & source[13]))
            & (((source[32] ^ _U32) & source[30]) ^ ((source[32] ^ _U32) & source[31]) ^ (source[30] & source[31]))
        )
        ^ (
            (((source[14] ^ _U32) & source[12]) ^ ((source[14] ^ _U32) & source[13]) ^ (source[12] & source[13]))
            & (((source[50] ^ _U32) & source[48]) ^ ((source[50] ^ _U32) & source[49]) ^ (source[48] & source[49]))
        )
        ^ (
            (((source[32] ^ _U32) & source[30]) ^ ((source[32] ^ _U32) & source[31]) ^ (source[30] & source[31]))
            & (((source[50] ^ _U32) & source[48]) ^ ((source[50] ^ _U32) & source[49]) ^ (source[48] & source[49]))
        )
    ) & _U32
    L4_4 = (
        (source[13] ^ ((source[14] ^ source[13]) & source[12]))
        ^ (source[31] ^ ((source[32] ^ source[31]) & source[30]))
        ^ (source[49] ^ ((source[50] ^ source[49]) & source[48]))
    ) & _U32
    L4_5 = (
        ((source[13] ^ ((source[14] ^ source[13]) & source[12])) & (source[31] ^ ((source[32] ^ source[31]) & source[30])))
        ^ ((source[13] ^ ((source[14] ^ source[13]) & source[12])) & (source[49] ^ ((source[50] ^ source[49]) & source[48])))
        ^ ((source[31] ^ ((source[32] ^ source[31]) & source[30])) & (source[49] ^ ((source[50] ^ source[49]) & source[48])))
    ) & _U32
    L4_6 = (
        (source[12] ^ (((source[13] ^ _U32) ^ source[12]) & source[14]))
        ^ (source[30] ^ (((source[31] ^ _U32) ^ source[30]) & source[32]))
        ^ (source[48] ^ (((source[49] ^ _U32) ^ source[48]) & source[50]))
    ) & _U32
    L4_7 = (
        (source[13] ^ ((source[12] ^ source[13]) & source[14]))
        ^ (source[31] ^ ((source[30] ^ source[31]) & source[32]))
        ^ (source[49] ^ ((source[48] ^ source[49]) & source[50]))
    ) & _U32
    L4_8 = (
        (
            (source[12] ^ (((source[13] ^ _U32) ^ source[12]) & source[14]))
            & (source[30] ^ (((source[31] ^ _U32) ^ source[30]) & source[32]))
        )
        ^ (
            (source[12] ^ (((source[13] ^ _U32) ^ source[12]) & source[14]))
            & (source[48] ^ (((source[49] ^ _U32) ^ source[48]) & source[50]))
        )
        ^ (
            (source[30] ^ (((source[31] ^ _U32) ^ source[30]) & source[32]))
            & (source[48] ^ (((source[49] ^ _U32) ^ source[48]) & source[50]))
        )
    ) & _U32
    L4_9 = (
        (source[12] ^ ((source[14] ^ source[12]) & source[13]))
        ^ (source[30] ^ ((source[32] ^ source[30]) & source[31]))
        ^ (source[48] ^ ((source[50] ^ source[48]) & source[49]))
    ) & _U32
    L4_10 = (
        ((source[12] ^ ((source[14] ^ source[12]) & source[13])) & (source[30] ^ ((source[32] ^ source[30]) & source[31])))
        ^ ((source[12] ^ ((source[14] ^ source[12]) & source[13])) & (source[48] ^ ((source[50] ^ source[48]) & source[49])))
        ^ ((source[30] ^ ((source[32] ^ source[30]) & source[31])) & (source[48] ^ ((source[50] ^ source[48]) & source[49])))
    ) & _U32
    L4_11 = (
        (source[13] ^ (((source[14] ^ _U32) ^ source[13]) & source[12]))
        ^ (source[31] ^ (((source[32] ^ _U32) ^ source[31]) & source[30]))
        ^ (source[49] ^ (((source[50] ^ _U32) ^ source[49]) & source[48]))
    ) & _U32
    L4_12 = (
        (
            (source[13] ^ (((source[14] ^ _U32) ^ source[13]) & source[12]))
            & (source[31] ^ (((source[32] ^ _U32) ^ source[31]) & source[30]))
        )
        ^ (
            (source[13] ^ (((source[14] ^ _U32) ^ source[13]) & source[12]))
            & (source[49] ^ (((source[50] ^ _U32) ^ source[49]) & source[48]))
        )
        ^ (
            (source[31] ^ (((source[32] ^ _U32) ^ source[31]) & source[30]))
            & (source[49] ^ (((source[50] ^ _U32) ^ source[49]) & source[48]))
        )
    ) & _U32
    L4_13 = (
        (source[12] ^ (((source[14] ^ _U32) ^ source[12]) & source[13]))
        ^ (source[30] ^ (((source[32] ^ _U32) ^ source[30]) & source[31]))
        ^ (source[48] ^ (((source[50] ^ _U32) ^ source[48]) & source[49]))
    ) & _U32
    L4_14 = (
        (
            (source[12] ^ (((source[14] ^ _U32) ^ source[12]) & source[13]))
            & (source[30] ^ (((source[32] ^ _U32) ^ source[30]) & source[31]))
        )
        ^ (
            (source[12] ^ (((source[14] ^ _U32) ^ source[12]) & source[13]))
            & (source[48] ^ (((source[50] ^ _U32) ^ source[48]) & source[49]))
        )
        ^ (
            (source[30] ^ (((source[32] ^ _U32) ^ source[30]) & source[31]))
            & (source[48] ^ (((source[50] ^ _U32) ^ source[48]) & source[49]))
        )
    ) & _U32
    L4_15 = (
        (source[14] ^ ((source[12] ^ source[14]) & source[13]))
        ^ (source[32] ^ ((source[30] ^ source[32]) & source[31]))
        ^ (source[50] ^ ((source[48] ^ source[50]) & source[49]))
    ) & _U32
    L4_16 = (
        ((source[14] ^ ((source[12] ^ source[14]) & source[13])) & (source[32] ^ ((source[30] ^ source[32]) & source[31])))
        ^ ((source[14] ^ ((source[12] ^ source[14]) & source[13])) & (source[50] ^ ((source[48] ^ source[50]) & source[49])))
        ^ ((source[32] ^ ((source[30] ^ source[32]) & source[31])) & (source[50] ^ ((source[48] ^ source[50]) & source[49])))
    ) & _U32
    L4_17 = (
        ((source[12] & source[13]) ^ (source[12] & source[14]) ^ (source[13] & source[14]))
        ^ ((source[30] & source[31]) ^ (source[30] & source[32]) ^ (source[31] & source[32]))
        ^ ((source[48] & source[49]) ^ (source[48] & source[50]) ^ (source[49] & source[50]))
    ) & _U32
    L4_18 = (
        (
            ((source[12] & source[13]) ^ (source[12] & source[14]) ^ (source[13] & source[14]))
            & ((source[30] & source[31]) ^ (source[30] & source[32]) ^ (source[31] & source[32]))
        )
        ^ (
            ((source[12] & source[13]) ^ (source[12] & source[14]) ^ (source[13] & source[14]))
            & ((source[48] & source[49]) ^ (source[48] & source[50]) ^ (source[49] & source[50]))
        )
        ^ (
            ((source[30] & source[31]) ^ (source[30] & source[32]) ^ (source[31] & source[32]))
            & ((source[48] & source[49]) ^ (source[48] & source[50]) ^ (source[49] & source[50]))
        )
    ) & _U32
    L4_19 = (
        (source[14] ^ (((source[12] ^ _U32) ^ source[14]) & source[13]))
        ^ (source[32] ^ (((source[30] ^ _U32) ^ source[32]) & source[31]))
        ^ (source[50] ^ (((source[48] ^ _U32) ^ source[50]) & source[49]))
    ) & _U32
    L4_20 = (
        (
            (source[14] ^ (((source[12] ^ _U32) ^ source[14]) & source[13]))
            & (source[32] ^ (((source[30] ^ _U32) ^ source[32]) & source[31]))
        )
        ^ (
            (source[14] ^ (((source[12] ^ _U32) ^ source[14]) & source[13]))
            & (source[50] ^ (((source[48] ^ _U32) ^ source[50]) & source[49]))
        )
        ^ (
            (source[32] ^ (((source[30] ^ _U32) ^ source[32]) & source[31]))
            & (source[50] ^ (((source[48] ^ _U32) ^ source[50]) & source[49]))
        )
    ) & _U32
    L4_21 = (
        (source[12] ^ ((source[13] ^ source[12]) & source[14]))
        ^ (source[30] ^ ((source[31] ^ source[30]) & source[32]))
        ^ (source[48] ^ ((source[49] ^ source[48]) & source[50]))
    ) & _U32
    L4_22 = (
        ((source[12] ^ ((source[13] ^ source[12]) & source[14])) & (source[30] ^ ((source[31] ^ source[30]) & source[32])))
        ^ ((source[12] ^ ((source[13] ^ source[12]) & source[14])) & (source[48] ^ ((source[49] ^ source[48]) & source[50])))
        ^ ((source[30] ^ ((source[31] ^ source[30]) & source[32])) & (source[48] ^ ((source[49] ^ source[48]) & source[50])))
    ) & _U32
    L4_23 = (
        (source[13] ^ (((source[12] ^ _U32) ^ source[13]) & source[14]))
        ^ (source[31] ^ (((source[30] ^ _U32) ^ source[31]) & source[32]))
        ^ (source[49] ^ (((source[48] ^ _U32) ^ source[49]) & source[50]))
    ) & _U32
    L4_24 = (
        (
            (source[13] ^ (((source[12] ^ _U32) ^ source[13]) & source[14]))
            & (source[31] ^ (((source[30] ^ _U32) ^ source[31]) & source[32]))
        )
        ^ (
            (source[13] ^ (((source[12] ^ _U32) ^ source[13]) & source[14]))
            & (source[49] ^ (((source[48] ^ _U32) ^ source[49]) & source[50]))
        )
        ^ (
            (source[31] ^ (((source[30] ^ _U32) ^ source[31]) & source[32]))
            & (source[49] ^ (((source[48] ^ _U32) ^ source[49]) & source[50]))
        )
    ) & _U32
    L4_25 = (
        (source[14] ^ ((source[13] ^ source[14]) & source[12]))
        ^ (source[32] ^ ((source[31] ^ source[32]) & source[30]))
        ^ (source[50] ^ ((source[49] ^ source[50]) & source[48]))
    ) & _U32
    L4_26 = (
        ((source[14] ^ ((source[13] ^ source[14]) & source[12])) & (source[32] ^ ((source[31] ^ source[32]) & source[30])))
        ^ ((source[14] ^ ((source[13] ^ source[14]) & source[12])) & (source[50] ^ ((source[49] ^ source[50]) & source[48])))
        ^ ((source[32] ^ ((source[31] ^ source[32]) & source[30])) & (source[50] ^ ((source[49] ^ source[50]) & source[48])))
    ) & _U32
    L4_27 = (
        ((source[13] ^ ((source[12] ^ source[13]) & source[14])) & (source[31] ^ ((source[30] ^ source[31]) & source[32])))
        ^ ((source[13] ^ ((source[12] ^ source[13]) & source[14])) & (source[49] ^ ((source[48] ^ source[49]) & source[50])))
        ^ ((source[31] ^ ((source[30] ^ source[31]) & source[32])) & (source[49] ^ ((source[48] ^ source[49]) & source[50])))
    ) & _U32
    L4_28 = (
        (((source[12] ^ _U32) & source[13]) ^ ((source[12] ^ _U32) & source[14]) ^ (source[13] & source[14]))
        ^ (((source[30] ^ _U32) & source[31]) ^ ((source[30] ^ _U32) & source[32]) ^ (source[31] & source[32]))
        ^ (((source[48] ^ _U32) & source[49]) ^ ((source[48] ^ _U32) & source[50]) ^ (source[49] & source[50]))
    ) & _U32
    L4_29 = (
        (
            (((source[12] ^ _U32) & source[13]) ^ ((source[12] ^ _U32) & source[14]) ^ (source[13] & source[14]))
            & (((source[30] ^ _U32) & source[31]) ^ ((source[30] ^ _U32) & source[32]) ^ (source[31] & source[32]))
        )
        ^ (
            (((source[12] ^ _U32) & source[13]) ^ ((source[12] ^ _U32) & source[14]) ^ (source[13] & source[14]))
            & (((source[48] ^ _U32) & source[49]) ^ ((source[48] ^ _U32) & source[50]) ^ (source[49] & source[50]))
        )
        ^ (
            (((source[30] ^ _U32) & source[31]) ^ ((source[30] ^ _U32) & source[32]) ^ (source[31] & source[32]))
            & (((source[48] ^ _U32) & source[49]) ^ ((source[48] ^ _U32) & source[50]) ^ (source[49] & source[50]))
        )
    ) & _U32
    L4_30 = (
        (((source[13] ^ _U32) & source[12]) ^ ((source[13] ^ _U32) & source[14]) ^ (source[12] & source[14]))
        ^ (((source[31] ^ _U32) & source[30]) ^ ((source[31] ^ _U32) & source[32]) ^ (source[30] & source[32]))
        ^ (((source[49] ^ _U32) & source[48]) ^ ((source[49] ^ _U32) & source[50]) ^ (source[48] & source[50]))
    ) & _U32
    L4_31 = (
        (
            (((source[13] ^ _U32) & source[12]) ^ ((source[13] ^ _U32) & source[14]) ^ (source[12] & source[14]))
            & (((source[31] ^ _U32) & source[30]) ^ ((source[31] ^ _U32) & source[32]) ^ (source[30] & source[32]))
        )
        ^ (
            (((source[13] ^ _U32) & source[12]) ^ ((source[13] ^ _U32) & source[14]) ^ (source[12] & source[14]))
            & (((source[49] ^ _U32) & source[48]) ^ ((source[49] ^ _U32) & source[50]) ^ (source[48] & source[50]))
        )
        ^ (
            (((source[31] ^ _U32) & source[30]) ^ ((source[31] ^ _U32) & source[32]) ^ (source[30] & source[32]))
            & (((source[49] ^ _U32) & source[48]) ^ ((source[49] ^ _U32) & source[50]) ^ (source[48] & source[50]))
        )
    ) & _U32
    L5_1 = (
        (((source[17] ^ _U32) & source[15]) ^ ((source[17] ^ _U32) & source[16]) ^ (source[15] & source[16]))
        ^ (((source[35] ^ _U32) & source[33]) ^ ((source[35] ^ _U32) & source[34]) ^ (source[33] & source[34]))
        ^ (((source[53] ^ _U32) & source[51]) ^ ((source[53] ^ _U32) & source[52]) ^ (source[51] & source[52]))
    ) & _U32
    L5_3 = (
        (
            (((source[17] ^ _U32) & source[15]) ^ ((source[17] ^ _U32) & source[16]) ^ (source[15] & source[16]))
            & (((source[35] ^ _U32) & source[33]) ^ ((source[35] ^ _U32) & source[34]) ^ (source[33] & source[34]))
        )
        ^ (
            (((source[17] ^ _U32) & source[15]) ^ ((source[17] ^ _U32) & source[16]) ^ (source[15] & source[16]))
            & (((source[53] ^ _U32) & source[51]) ^ ((source[53] ^ _U32) & source[52]) ^ (source[51] & source[52]))
        )
        ^ (
            (((source[35] ^ _U32) & source[33]) ^ ((source[35] ^ _U32) & source[34]) ^ (source[33] & source[34]))
            & (((source[53] ^ _U32) & source[51]) ^ ((source[53] ^ _U32) & source[52]) ^ (source[51] & source[52]))
        )
    ) & _U32
    L5_7 = (
        (source[16] ^ ((source[15] ^ source[16]) & source[17]))
        ^ (source[34] ^ ((source[33] ^ source[34]) & source[35]))
        ^ (source[52] ^ ((source[51] ^ source[52]) & source[53]))
    ) & _U32
    L5_13 = (
        (source[15] ^ (((source[17] ^ _U32) ^ source[15]) & source[16]))
        ^ (source[33] ^ (((source[35] ^ _U32) ^ source[33]) & source[34]))
        ^ (source[51] ^ (((source[53] ^ _U32) ^ source[51]) & source[52]))
    ) & _U32
    L5_14 = (
        (
            (source[15] ^ (((source[17] ^ _U32) ^ source[15]) & source[16]))
            & (source[33] ^ (((source[35] ^ _U32) ^ source[33]) & source[34]))
        )
        ^ (
            (source[15] ^ (((source[17] ^ _U32) ^ source[15]) & source[16]))
            & (source[51] ^ (((source[53] ^ _U32) ^ source[51]) & source[52]))
        )
        ^ (
            (source[33] ^ (((source[35] ^ _U32) ^ source[33]) & source[34]))
            & (source[51] ^ (((source[53] ^ _U32) ^ source[51]) & source[52]))
        )
    ) & _U32
    L5_15 = (
        (source[17] ^ ((source[15] ^ source[17]) & source[16]))
        ^ (source[35] ^ ((source[33] ^ source[35]) & source[34]))
        ^ (source[53] ^ ((source[51] ^ source[53]) & source[52]))
    ) & _U32
    L5_16 = (
        ((source[17] ^ ((source[15] ^ source[17]) & source[16])) & (source[35] ^ ((source[33] ^ source[35]) & source[34])))
        ^ ((source[17] ^ ((source[15] ^ source[17]) & source[16])) & (source[53] ^ ((source[51] ^ source[53]) & source[52])))
        ^ ((source[35] ^ ((source[33] ^ source[35]) & source[34])) & (source[53] ^ ((source[51] ^ source[53]) & source[52])))
    ) & _U32
    L5_19 = (
        (source[17] ^ (((source[15] ^ _U32) ^ source[17]) & source[16]))
        ^ (source[35] ^ (((source[33] ^ _U32) ^ source[35]) & source[34]))
        ^ (source[53] ^ (((source[51] ^ _U32) ^ source[53]) & source[52]))
    ) & _U32
    L5_20 = (
        (
            (source[17] ^ (((source[15] ^ _U32) ^ source[17]) & source[16]))
            & (source[35] ^ (((source[33] ^ _U32) ^ source[35]) & source[34]))
        )
        ^ (
            (source[17] ^ (((source[15] ^ _U32) ^ source[17]) & source[16]))
            & (source[53] ^ (((source[51] ^ _U32) ^ source[53]) & source[52]))
        )
        ^ (
            (source[35] ^ (((source[33] ^ _U32) ^ source[35]) & source[34]))
            & (source[53] ^ (((source[51] ^ _U32) ^ source[53]) & source[52]))
        )
    ) & _U32
    L5_21 = (
        (source[15] ^ ((source[16] ^ source[15]) & source[17]))
        ^ (source[33] ^ ((source[34] ^ source[33]) & source[35]))
        ^ (source[51] ^ ((source[52] ^ source[51]) & source[53]))
    ) & _U32
    L5_25 = (
        (source[17] ^ ((source[16] ^ source[17]) & source[15]))
        ^ (source[35] ^ ((source[34] ^ source[35]) & source[33]))
        ^ (source[53] ^ ((source[52] ^ source[53]) & source[51]))
    ) & _U32
    L5_26 = (
        ((source[17] ^ ((source[16] ^ source[17]) & source[15])) & (source[35] ^ ((source[34] ^ source[35]) & source[33])))
        ^ ((source[17] ^ ((source[16] ^ source[17]) & source[15])) & (source[53] ^ ((source[52] ^ source[53]) & source[51])))
        ^ ((source[35] ^ ((source[34] ^ source[35]) & source[33])) & (source[53] ^ ((source[52] ^ source[53]) & source[51])))
    ) & _U32
    L5_27 = (
        ((source[16] ^ ((source[15] ^ source[16]) & source[17])) & (source[34] ^ ((source[33] ^ source[34]) & source[35])))
        ^ ((source[16] ^ ((source[15] ^ source[16]) & source[17])) & (source[52] ^ ((source[51] ^ source[52]) & source[53])))
        ^ ((source[34] ^ ((source[33] ^ source[34]) & source[35])) & (source[52] ^ ((source[51] ^ source[52]) & source[53])))
    ) & _U32
    L5_28 = (
        (((source[15] ^ _U32) & source[16]) ^ ((source[15] ^ _U32) & source[17]) ^ (source[16] & source[17]))
        ^ (((source[33] ^ _U32) & source[34]) ^ ((source[33] ^ _U32) & source[35]) ^ (source[34] & source[35]))
        ^ (((source[51] ^ _U32) & source[52]) ^ ((source[51] ^ _U32) & source[53]) ^ (source[52] & source[53]))
    ) & _U32
    L5_29 = (
        (
            (((source[15] ^ _U32) & source[16]) ^ ((source[15] ^ _U32) & source[17]) ^ (source[16] & source[17]))
            & (((source[33] ^ _U32) & source[34]) ^ ((source[33] ^ _U32) & source[35]) ^ (source[34] & source[35]))
        )
        ^ (
            (((source[15] ^ _U32) & source[16]) ^ ((source[15] ^ _U32) & source[17]) ^ (source[16] & source[17]))
            & (((source[51] ^ _U32) & source[52]) ^ ((source[51] ^ _U32) & source[53]) ^ (source[52] & source[53]))
        )
        ^ (
            (((source[33] ^ _U32) & source[34]) ^ ((source[33] ^ _U32) & source[35]) ^ (source[34] & source[35]))
            & (((source[51] ^ _U32) & source[52]) ^ ((source[51] ^ _U32) & source[53]) ^ (source[52] & source[53]))
        )
    ) & _U32
    L5_30 = (
        (((source[16] ^ _U32) & source[15]) ^ ((source[16] ^ _U32) & source[17]) ^ (source[15] & source[17]))
        ^ (((source[34] ^ _U32) & source[33]) ^ ((source[34] ^ _U32) & source[35]) ^ (source[33] & source[35]))
        ^ (((source[52] ^ _U32) & source[51]) ^ ((source[52] ^ _U32) & source[53]) ^ (source[51] & source[53]))
    ) & _U32
    L5_31 = (
        (
            (((source[16] ^ _U32) & source[15]) ^ ((source[16] ^ _U32) & source[17]) ^ (source[15] & source[17]))
            & (((source[34] ^ _U32) & source[33]) ^ ((source[34] ^ _U32) & source[35]) ^ (source[33] & source[35]))
        )
        ^ (
            (((source[16] ^ _U32) & source[15]) ^ ((source[16] ^ _U32) & source[17]) ^ (source[15] & source[17]))
            & (((source[52] ^ _U32) & source[51]) ^ ((source[52] ^ _U32) & source[53]) ^ (source[51] & source[53]))
        )
        ^ (
            (((source[34] ^ _U32) & source[33]) ^ ((source[34] ^ _U32) & source[35]) ^ (source[33] & source[35]))
            & (((source[52] ^ _U32) & source[51]) ^ ((source[52] ^ _U32) & source[53]) ^ (source[51] & source[53]))
        )
    ) & _U32

    first = 0
    second = 0
    v0 = (L0_0 >> 0) & 1
    v1 = (L0_1 >> 1) & 1
    first |= (1 ^ v0 ^ v1) << 0
    second |= (((L0_2 >> 0) & 1) ^ v0 & v1) << 1
    v0 = (L0_3 >> 1) & 1
    v1 = (L0_4 >> 2) & 1
    first |= (0 ^ v0 ^ v1) << 1
    second |= (1 ^ v0 ^ v1 ^ v0 & v1) << 2
    v0 = (L0_5 >> 2) & 1
    v1 = (L0_6 >> 3) & 1
    first |= (0 ^ v0 ^ v1) << 2
    second |= (1 ^ v0 ^ v1 ^ v0 & v1) << 3
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_8 >> 3) & 1
    v2 = (L0_9 >> 4) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 3
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 4
    v0 = (L0_10 >> 4) & 1
    v1 = (L0_11 >> 5) & 1
    first |= (0 ^ v0 ^ v1) << 4
    second |= (1 ^ v0 ^ v1 ^ v0 & v1) << 5
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_12 >> 5) & 1
    v2 = (L0_13 >> 6) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 5
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 6
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_14 >> 6) & 1
    v2 = (L0_1 >> 7) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 6
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 7
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_3 >> 7) & 1
    v2 = (L0_15 >> 8) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 7
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 8
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_16 >> 8) & 1
    v2 = (L0_17 >> 9) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 8
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 9
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_18 >> 9) & 1
    v2 = (L0_19 >> 10) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 9
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 10
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_20 >> 10) & 1
    v2 = (L0_4 >> 11) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 10
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 11
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_5 >> 11) & 1
    v2 = (L0_21 >> 12) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 11
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 12
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_22 >> 12) & 1
    v2 = (L0_6 >> 13) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 12
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 13
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_8 >> 13) & 1
    v2 = (L0_1 >> 14) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 13
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 14
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_3 >> 14) & 1
    v2 = (L0_23 >> 15) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 14
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 15
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_24 >> 15) & 1
    v2 = (L0_15 >> 16) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 15
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 16
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_16 >> 16) & 1
    v2 = (L0_25 >> 17) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 16
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 17
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_26 >> 17) & 1
    v2 = (L0_17 >> 18) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 17
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 18
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_18 >> 18) & 1
    v2 = (L0_4 >> 19) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 18
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 19
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_5 >> 19) & 1
    v2 = (L0_9 >> 20) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 19
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 20
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_10 >> 20) & 1
    v2 = (L0_7 >> 21) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 20
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 21
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_27 >> 21) & 1
    v2 = (L0_1 >> 22) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 21
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 22
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_3 >> 22) & 1
    v2 = (L0_28 >> 23) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 22
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 23
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_29 >> 23) & 1
    v2 = (L0_9 >> 24) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 23
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 24
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_10 >> 24) & 1
    v2 = (L0_23 >> 25) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 24
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 25
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_24 >> 25) & 1
    v2 = (L0_25 >> 26) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 25
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 26
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_26 >> 26) & 1
    v2 = (L0_17 >> 27) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 26
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 27
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_18 >> 27) & 1
    v2 = (L0_28 >> 28) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 27
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 28
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_29 >> 28) & 1
    v2 = (L0_13 >> 29) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 28
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 29
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_14 >> 29) & 1
    v2 = (L0_17 >> 30) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 29
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 30
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_18 >> 30) & 1
    v2 = (L0_30 >> 31) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 30
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 31
    v0 = (L0_7 >> 0) & 1
    v1 = (L0_31 >> 31) & 1
    v2 = (L1_28 >> 0) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 31
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 32
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_29 >> 0) & 1
    v2 = (L1_1 >> 1) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 32
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 33
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_3 >> 1) & 1
    v2 = (L1_30 >> 2) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 33
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 34
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_31 >> 2) & 1
    v2 = (L1_13 >> 3) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 34
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 35
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_14 >> 3) & 1
    v2 = (L1_9 >> 4) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 35
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 36
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_10 >> 4) & 1
    v2 = (L1_13 >> 5) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 36
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 37
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_14 >> 5) & 1
    v2 = (L1_25 >> 6) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 37
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 38
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_26 >> 6) & 1
    v2 = (L1_19 >> 7) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 38
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 39
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_20 >> 7) & 1
    v2 = (L1_30 >> 8) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 39
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 40
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_31 >> 8) & 1
    v2 = (L1_19 >> 9) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 40
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 41
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_20 >> 9) & 1
    v2 = (L1_19 >> 10) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 41
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 42
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_20 >> 10) & 1
    v2 = (L1_28 >> 11) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 42
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 43
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_29 >> 11) & 1
    v2 = (L1_28 >> 12) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 43
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 44
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_29 >> 12) & 1
    v2 = (L1_25 >> 13) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 44
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 45
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_26 >> 13) & 1
    v2 = (L1_13 >> 14) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 45
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 46
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_14 >> 14) & 1
    v2 = (L1_13 >> 15) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 46
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 47
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_14 >> 15) & 1
    v2 = (L1_17 >> 16) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 47
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 48
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_18 >> 16) & 1
    v2 = (L1_30 >> 17) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 48
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 49
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_31 >> 17) & 1
    v2 = (L1_1 >> 18) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 49
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 50
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_3 >> 18) & 1
    v2 = (L1_11 >> 19) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 50
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 51
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_12 >> 19) & 1
    v2 = (L1_1 >> 20) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 51
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 52
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_3 >> 20) & 1
    v2 = (L1_30 >> 21) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 52
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 53
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_31 >> 21) & 1
    v2 = (L1_21 >> 22) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 53
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 54
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_22 >> 22) & 1
    v2 = (L1_30 >> 23) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 54
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 55
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_31 >> 23) & 1
    v2 = (L1_4 >> 24) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 55
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 56
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_5 >> 24) & 1
    v2 = (L1_25 >> 25) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 56
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 57
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_26 >> 25) & 1
    v2 = (L1_6 >> 26) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 57
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 58
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_8 >> 26) & 1
    v2 = (L1_15 >> 27) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 58
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 59
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_16 >> 27) & 1
    v2 = (L1_19 >> 28) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 59
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 60
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_20 >> 28) & 1
    v2 = (L1_21 >> 29) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 60
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 61
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_22 >> 29) & 1
    v2 = (L1_25 >> 30) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 61
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 62
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_26 >> 30) & 1
    v2 = (L1_30 >> 31) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 62
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 63
    v0 = (L0_7 >> 0) & 1
    v1 = (L1_31 >> 31) & 1
    v2 = (L2_17 >> 0) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 63
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 64
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_18 >> 0) & 1
    v2 = (L2_6 >> 1) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 64
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 65
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_8 >> 1) & 1
    v2 = (L2_25 >> 2) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 65
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 66
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_26 >> 2) & 1
    v2 = (L2_9 >> 3) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 66
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 67
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_10 >> 3) & 1
    v2 = (L2_1 >> 4) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 67
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 68
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_3 >> 4) & 1
    v2 = (L2_15 >> 5) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 68
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 69
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_16 >> 5) & 1
    v2 = (L2_11 >> 6) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 69
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 70
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_12 >> 6) & 1
    v2 = (L2_11 >> 7) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 70
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 71
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_12 >> 7) & 1
    v2 = (L2_28 >> 8) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 71
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 72
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_29 >> 8) & 1
    v2 = (L2_11 >> 9) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 72
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 73
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_12 >> 9) & 1
    v2 = (L2_9 >> 10) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 73
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 74
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_10 >> 10) & 1
    v2 = (L2_23 >> 11) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 74
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 75
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_24 >> 11) & 1
    v2 = (L2_6 >> 12) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 75
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 76
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_8 >> 12) & 1
    v2 = (L2_9 >> 13) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 76
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 77
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_10 >> 13) & 1
    v2 = (L2_15 >> 14) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 77
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 78
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_16 >> 14) & 1
    v2 = (L2_30 >> 15) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 78
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 79
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_31 >> 15) & 1
    v2 = (L2_7 >> 16) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 79
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 80
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_27 >> 16) & 1
    v2 = (L2_6 >> 17) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 80
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 81
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_8 >> 17) & 1
    v2 = (L2_23 >> 18) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 81
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 82
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_24 >> 18) & 1
    v2 = (L2_1 >> 19) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 82
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 83
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_3 >> 19) & 1
    v2 = (L2_1 >> 20) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 83
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 84
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_3 >> 20) & 1
    v2 = (L2_23 >> 21) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 84
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 85
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_24 >> 21) & 1
    v2 = (L2_19 >> 22) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 85
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 86
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_20 >> 22) & 1
    v2 = (L2_23 >> 23) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 86
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 87
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_24 >> 23) & 1
    v2 = (L2_17 >> 24) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 87
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 88
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_18 >> 24) & 1
    v2 = (L2_17 >> 25) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 88
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 89
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_18 >> 25) & 1
    v2 = (L2_21 >> 26) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 89
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 90
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_22 >> 26) & 1
    v2 = (L2_19 >> 27) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 90
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 91
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_20 >> 27) & 1
    v2 = (L2_1 >> 28) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 91
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 92
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_3 >> 28) & 1
    v2 = (L2_17 >> 29) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 92
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 93
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_18 >> 29) & 1
    v2 = (L2_11 >> 30) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 93
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 94
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_12 >> 30) & 1
    v2 = (L2_19 >> 31) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 94
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 95
    v0 = (L0_7 >> 0) & 1
    v1 = (L2_20 >> 31) & 1
    v2 = (L3_30 >> 0) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 95
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 96
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_31 >> 0) & 1
    v2 = (L3_17 >> 1) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 96
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 97
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_18 >> 1) & 1
    v2 = (L3_19 >> 2) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 97
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 98
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_20 >> 2) & 1
    v2 = (L3_17 >> 3) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 98
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 99
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_18 >> 3) & 1
    v2 = (L3_11 >> 4) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 99
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 100
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_12 >> 4) & 1
    v2 = (L3_4 >> 5) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 100
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 101
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_5 >> 5) & 1
    v2 = (L3_1 >> 6) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 101
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 102
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_3 >> 6) & 1
    v2 = (L3_17 >> 7) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 102
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 103
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_18 >> 7) & 1
    v2 = (L3_9 >> 8) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 103
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 104
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_10 >> 8) & 1
    v2 = (L3_19 >> 9) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 104
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 105
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_20 >> 9) & 1
    v2 = (L3_15 >> 10) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 105
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 106
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_16 >> 10) & 1
    v2 = (L3_19 >> 11) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 106
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 107
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_20 >> 11) & 1
    v2 = (L3_7 >> 12) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 107
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 108
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_27 >> 12) & 1
    v2 = (L3_15 >> 13) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 108
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 109
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_16 >> 13) & 1
    v2 = (L3_23 >> 14) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 109
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 110
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_24 >> 14) & 1
    v2 = (L3_28 >> 15) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 110
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 111
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_29 >> 15) & 1
    v2 = (L3_30 >> 16) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 111
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 112
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_31 >> 16) & 1
    v2 = (L3_23 >> 17) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 112
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 113
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_24 >> 17) & 1
    v2 = (L3_30 >> 18) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 113
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 114
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_31 >> 18) & 1
    v2 = (L3_4 >> 19) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 114
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 115
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_5 >> 19) & 1
    v2 = (L3_7 >> 20) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 115
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 116
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_27 >> 20) & 1
    v2 = (L3_15 >> 21) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 116
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 117
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_16 >> 21) & 1
    v2 = (L3_15 >> 22) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 117
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 118
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_16 >> 22) & 1
    v2 = (L3_25 >> 23) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 118
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 119
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_26 >> 23) & 1
    v2 = (L3_21 >> 24) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 119
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 120
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_22 >> 24) & 1
    v2 = (L3_4 >> 25) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 120
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 121
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_5 >> 25) & 1
    v2 = (L3_23 >> 26) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 121
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 122
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_24 >> 26) & 1
    v2 = (L3_17 >> 27) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 122
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 123
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_18 >> 27) & 1
    v2 = (L3_9 >> 28) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 123
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 124
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_10 >> 28) & 1
    v2 = (L3_17 >> 29) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 124
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 125
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_18 >> 29) & 1
    v2 = (L3_30 >> 30) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 125
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 126
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_31 >> 30) & 1
    v2 = (L3_28 >> 31) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 126
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 127
    v0 = (L0_7 >> 0) & 1
    v1 = (L3_29 >> 31) & 1
    v2 = (L4_17 >> 0) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 127
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 128
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_18 >> 0) & 1
    v2 = (L4_1 >> 1) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 128
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 129
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_3 >> 1) & 1
    v2 = (L4_6 >> 2) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 129
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 130
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_8 >> 2) & 1
    v2 = (L4_17 >> 3) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 130
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 131
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_18 >> 3) & 1
    v2 = (L4_1 >> 4) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 131
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 132
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_3 >> 4) & 1
    v2 = (L4_9 >> 5) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 132
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 133
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_10 >> 5) & 1
    v2 = (L4_6 >> 6) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 133
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 134
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_8 >> 6) & 1
    v2 = (L4_30 >> 7) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 134
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 135
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_31 >> 7) & 1
    v2 = (L4_11 >> 8) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 135
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 136
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_12 >> 8) & 1
    v2 = (L4_23 >> 9) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 136
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 137
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_24 >> 9) & 1
    v2 = (L4_7 >> 10) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 137
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 138
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_27 >> 10) & 1
    v2 = (L4_1 >> 11) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 138
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 139
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_3 >> 11) & 1
    v2 = (L4_28 >> 12) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 139
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 140
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_29 >> 12) & 1
    v2 = (L4_11 >> 13) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 140
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 141
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_12 >> 13) & 1
    v2 = (L4_21 >> 14) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 141
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 142
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_22 >> 14) & 1
    v2 = (L4_11 >> 15) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 142
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 143
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_12 >> 15) & 1
    v2 = (L4_13 >> 16) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 143
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 144
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_14 >> 16) & 1
    v2 = (L4_17 >> 17) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 144
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 145
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_18 >> 17) & 1
    v2 = (L4_4 >> 18) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 145
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 146
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_5 >> 18) & 1
    v2 = (L4_1 >> 19) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 146
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 147
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_3 >> 19) & 1
    v2 = (L4_15 >> 20) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 147
    second |= (1 ^ v1 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 148
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_16 >> 20) & 1
    v2 = (L4_7 >> 21) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 148
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 149
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_27 >> 21) & 1
    v2 = (L4_7 >> 22) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 149
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 150
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_27 >> 22) & 1
    v2 = (L4_19 >> 23) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 150
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 151
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_20 >> 23) & 1
    v2 = (L4_7 >> 24) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 151
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 152
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_27 >> 24) & 1
    v2 = (L4_4 >> 25) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 152
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 153
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_5 >> 25) & 1
    v2 = (L4_1 >> 26) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 153
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 154
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_3 >> 26) & 1
    v2 = (L4_17 >> 27) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 154
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 155
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_18 >> 27) & 1
    v2 = (L4_28 >> 28) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 155
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 156
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_29 >> 28) & 1
    v2 = (L4_25 >> 29) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 156
    second |= (v0 ^ v0 & v1 ^ v2 ^ v0 & v2 ^ v1 & v2) << 157
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_26 >> 29) & 1
    v2 = (L4_23 >> 30) & 1
    first |= (0 ^ v0 ^ v1 ^ v2) << 157
    second |= (v0 & v1 ^ v0 & v2 ^ v1 & v2) << 158
    v0 = (L0_7 >> 0) & 1
    v1 = (L4_24 >> 30) & 1
    v2 = (L4_28 >> 31) & 1
    first |= (1 ^ v0 ^ v1 ^ v2) << 158
    second |= (v0 ^ v1 ^ v0 & v1 ^ v0 & v2 ^ v1 & v2) << 159
    v0 = (L4_29 >> 31) & 1
    v1 = (L5_15 >> 0) & 1
    first |= (0 ^ v0 ^ v1) << 159
    second |= (1 ^ v0 ^ v1 ^ v0 & v1) << 160
    v0 = (L5_16 >> 0) & 1
    v1 = (L5_30 >> 1) & 1
    first |= (0 ^ v0 ^ v1) << 160
    second |= (1 ^ v0 ^ v1 ^ v0 & v1) << 161
    v0 = (L5_31 >> 1) & 1
    v1 = (L5_13 >> 2) & 1
    first |= (0 ^ v0 ^ v1) << 161
    second |= (1 ^ v0 ^ v1 ^ v0 & v1) << 162
    v0 = (L5_14 >> 2) & 1
    v1 = (L5_25 >> 3) & 1
    first |= (1 ^ v0 ^ v1) << 162
    second |= (v1 ^ v0 & v1) << 163
    v0 = (L5_26 >> 3) & 1
    v1 = (L5_7 >> 4) & 1
    first |= (1 ^ v0 ^ v1) << 163
    second |= (v0 ^ v0 & v1) << 164
    v0 = (L5_27 >> 4) & 1
    v1 = (L5_28 >> 5) & 1
    first |= (1 ^ v0 ^ v1) << 164
    second |= (v1 ^ v0 & v1) << 165
    v0 = (L5_29 >> 5) & 1
    v1 = (L5_1 >> 6) & 1
    first |= (0 ^ v0 ^ v1) << 165
    second |= (v0 & v1) << 166
    v0 = (L5_3 >> 6) & 1
    v1 = (L5_19 >> 7) & 1
    first |= (0 ^ v0 ^ v1) << 166
    second |= (v0 & v1) << 167
    v0 = (L5_20 >> 7) & 1
    v1 = (L5_21 >> 8) & 1
    first |= (0 ^ v0 ^ v1) << 167

    return tuple(((first >> (28 * word)) & 0x0FFFFFFF) << 2 for word in range(6)) + tuple(
        ((second >> (28 * word)) & 0x0FFFFFFF) << 2 for word in range(6)
    )


def execute(destination: bytearray, source: bytes) -> None:
    """Write the twelve Monolith5 output words into destination[:48].

    Signature matches the retired ``_generated/monolith5.py`` entry point.
    """
    words = struct.unpack("<54I", bytes(source[:216]))
    destination[:48] = struct.pack("<12I", *execute_words(words))
