"""Compile the recovered Monolith5 gate/position model into flat Python source.

`tools/monolith5_gate_model.py` proved an exact per-bit formula for Monolith5,
but its runtime evaluator is a 168-iteration interpreter over the position
records (cache lookups, per-position subset loops). Benchmarking that
interpreter against the generated implementation showed it about 2.3-2.5x
slower despite an 8-9x smaller source (see MODEL_BENCHMARKS.md), and
MODEL_BENCHMARKS.md explicitly recommends "generat[ing] word-level
operations" before considering a runtime migration.

This tool does exactly that: it unrolls the interpreter into straight-line
Python — one local variable per unique (chunk, function) lane evaluation
(reused across positions, same as the interpreter's cache), then one
statement per of the 168 position accumulations, with the per-position
subset enumeration resolved at generation time instead of at runtime. No new
cryptanalysis: same formula, mechanical unrolling only.

Usage:
    python -m tools.compile_monolith5 --write
    python -m tools.compile_monolith5 --check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

_HERE = Path(__file__).parent


def _ruff_format(source: str) -> str:
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _load() -> tuple[list[dict[str, Any]], list[list[Any]]]:
    gate_model = json.loads((_HERE / "monolith5_gate_model.json").read_text(encoding="utf-8"))
    position_model = json.loads((_HERE / "monolith5_model.json").read_text(encoding="utf-8"))
    if gate_model["version"] != 1 or len(gate_model["functions"]) != 32:
        raise ValueError("unsupported Monolith5 gate model")
    entries = position_model["entries"]
    if len(entries) != 168:
        raise ValueError("invalid Monolith5 position model size")
    return gate_model["functions"], entries


def _lane_expression(chunk: int, function_id: int, function: dict[str, Any]) -> str:
    gate = function["gate"]
    order = function["order"]
    inversions = function["inversions"]
    combine = function["combine"]

    span_exprs = []
    for span in range(3):
        terms = []
        for position, source_index in enumerate(order):
            word_index = span * 18 + chunk * 3 + source_index
            if inversions & (1 << position):
                terms.append(f"(source[{word_index}] ^ _U32)")
            else:
                terms.append(f"source[{word_index}]")
        a, b, c = terms
        if gate == "choose":
            span_exprs.append(f"({b} ^ (({a} ^ {b}) & {c}))")
        elif gate == "majority":
            span_exprs.append(f"(({a} & {b}) ^ ({a} & {c}) ^ ({b} & {c}))")
        else:
            raise ValueError(f"unknown gate {gate!r}")
    s0, s1, s2 = span_exprs
    if combine == "xor3":
        return f"(({s0} ^ {s1} ^ {s2}) & _U32)"
    if combine == "majority":
        return f"((({s0} & {s1}) ^ ({s0} & {s2}) ^ ({s1} & {s2})) & _U32)"
    if combine == "or3":
        return f"(({s0} | {s1} | {s2}) & _U32)"
    if combine == "not_all_equal":
        return f"((({s0} | {s1} | {s2}) ^ ({s0} & {s1} & {s2})) & _U32)"
    raise ValueError(f"unknown combine {combine!r}")


def generate() -> str:
    functions, entries = _load()

    pairs: set[tuple[int, int]] = set()
    for _constant, components, _mask, residual in entries:
        for chunk, _bit, function_id in components:
            pairs.add((chunk, function_id))
        if residual is not None:
            chunk, _bit, function_id = residual
            pairs.add((chunk, function_id))

    lines: list[str] = [
        '"""Monolith5 — compiled, proven-equivalent runtime implementation.',
        "",
        "Mechanically generated by ``tools/compile_monolith5.py`` from the exact,",
        "exhaustively verified ``tools/monolith5_gate_model.json`` and",
        "``tools/monolith5_model.json`` formula (see MONOLITH5_ANALYSIS.md). This",
        "is the same per-bit formula as the interpreter in",
        "``tools/monolith5_gate_model.py``, unrolled into straight-line code to",
        "remove interpretation overhead — no new cryptanalysis. DO NOT EDIT —",
        "regenerate with ``python -m tools.compile_monolith5 --write``.",
        "",
        "This module is the runtime implementation used by",
        "``monolith_wrappers.py``. ``family0/_generated/monolith5.py``",
        "(HarpoS7-derived, MIT-licensed; see ``LICENSE-HarpoS7``) is kept only",
        "for provenance/audit and is no longer called here — a proven,",
        "byte-for-byte equivalent representation change per issue #1's",
        "acceptance criteria, not a behavior change. It is also about 1.6x",
        "smaller and about 2.2x faster than the generated implementation and",
        "needs no runtime JSON loading; see MODEL_BENCHMARKS.md.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import struct",
        "from collections.abc import Sequence",
        "",
        "_U32 = 0xFFFFFFFF",
        "",
        "",
        "def execute_words(source: Sequence[int]) -> tuple[int, ...]:",
        '    """Map 54 source words to twelve destination words."""',
        "    if len(source) < 54:",
        '        raise ValueError("Monolith5 requires at least 54 source words")',
        "",
    ]

    for chunk, function_id in sorted(pairs):
        expr = _lane_expression(chunk, function_id, functions[function_id])
        lines.append(f"    L{chunk}_{function_id} = {expr}")

    lines.append("")
    lines.append("    first = 0")
    lines.append("    second = 0")

    for position, (constant, components, second_mask, residual) in enumerate(entries):
        value_vars = []
        for index, (chunk, bit, function_id) in enumerate(components):
            name = f"v{index}"
            lines.append(f"    {name} = (L{chunk}_{function_id} >> {bit}) & 1")
            value_vars.append(name)

        first_terms = [str(constant), *value_vars]
        lines.append(f"    first |= ({' ^ '.join(first_terms)}) << {position}")

        if position < 167:
            second_terms = []
            if residual is not None:
                r_chunk, r_bit, r_function_id = residual
                second_terms.append(f"((L{r_chunk}_{r_function_id} >> {r_bit}) & 1)")
            count = len(value_vars)
            for subset in range(1 << count):
                if not second_mask & (1 << subset):
                    continue
                selected = [value_vars[index] for index in range(count) if subset & (1 << index)]
                second_terms.append(" & ".join(selected) if selected else "1")
            if second_terms:
                lines.append(f"    second |= ({' ^ '.join(second_terms)}) << {position + 1}")

    lines.append("")
    lines.append("    return tuple(((first >> (28 * word)) & 0x0FFFFFFF) << 2 for word in range(6)) + tuple(")
    lines.append("        ((second >> (28 * word)) & 0x0FFFFFFF) << 2 for word in range(6)")
    lines.append("    )")
    lines.append("")
    lines.append("")
    lines.append("def execute(destination: bytearray, source: bytes) -> None:")
    lines.append('    """Write the twelve Monolith5 output words into destination[:48].')
    lines.append("")
    lines.append("    Signature matches the retired ``_generated/monolith5.py`` entry point.")
    lines.append('    """')
    lines.append('    words = struct.unpack("<54I", bytes(source[:216]))')
    lines.append('    destination[:48] = struct.pack("<12I", *execute_words(words))')
    lines.append("")
    return "\n".join(lines)


_TARGET = _HERE.parent / "old" / "family0" / "monolith5_compact.py"


def compile_source() -> str:
    """Generate and ruff-format the Monolith5 runtime module source."""
    return _ruff_format(generate())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify monolith5_compact.py is up to date, without writing.")
    parser.add_argument("--write", action="store_true", help="Write the generated source to monolith5_compact.py.")
    args = parser.parse_args(argv)

    source = compile_source()
    if args.check:
        if not _TARGET.is_file() or _TARGET.read_text(encoding="utf-8") != source:
            print(f"{_TARGET} is out of date; regenerate with python -m tools.compile_monolith5 --write", file=sys.stderr)
            return 1
        print(f"{_TARGET.name} matches the source model")
        return 0
    if args.write:
        _TARGET.write_text(source, encoding="utf-8")
        print(f"wrote {_TARGET}")
        return 0
    sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
