"""Compile the recovered Monolith7 full decision model into flat Python source.

``tools/monolith7_full_model.py`` proved an exact per-bit ROBDD decision model
covering all 1,152 Monolith7 output bits (see MONOLITH7_ANALYSIS.md), but its
runtime evaluator walks each bit's decision diagram node by node (at most 22
decisions per bit) — benchmarking that interpreter against the generated
implementation showed it about 5.9x slower despite reusing shared nodes
(MODEL_BENCHMARKS.md). Compiling Monolith5's equivalent interpreter into flat
code fixed that same "interpretation overhead dominates" pattern, so this
tool tries the identical mechanical transform here: unroll each output bit's
decision-diagram walk into a straight-line expression, one local variable per
node actually reachable from that bit's root (using the shared "choose"
formula ``choose(high, low, selector) = low ^ ((high ^ low) & selector)``,
matching MONOLITH7_ANALYSIS.md's documented node equation), then combine the
32 bits of each output word with a single OR-shift expression. No new
cryptanalysis: same formula, mechanical unrolling only.

Unlike Monolith5, **this does not pay off** — see MODEL_BENCHMARKS.md. The
result is byte-exact but about 20x *slower* and about 60x larger than
generated code, because Monolith5's model was word-parallel (168 statements
each doing 32-bit-wide bitwise work) while Monolith7's full model is
bit-serial (1,152 independent bit computations, ~77,000 total node
evaluations with almost no cross-bit sharing) — unrolling just multiplies
per-statement Python overhead instead of removing it. The hand-written
interpreter loop is already more efficient per elementary operation than this
flat expansion. This module is kept as a benchmarked analysis reference
documenting that negative result, alongside ``tools/monolith7_full_model.py``
— it is not used by ``monolith_wrappers.py`` and is not a migration
candidate.

Usage:
    python -m tools.compile_monolith7 --write
    python -m tools.compile_monolith7 --check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

_HERE = Path(__file__).parent


def _ruff_format(source: str) -> str:
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _load() -> dict[str, Any]:
    data = json.loads((_HERE / "monolith7_full_model.json").read_text(encoding="utf-8"))
    if data["version"] != 1 or data["output_words"] != list(range(36)) or len(data["bits"]) != 1152:
        raise ValueError("unsupported Monolith7 full model")
    return data


def _reachable(nodes: list[list[int]], root: int) -> list[int]:
    """All non-terminal node indexes reachable from root, ascending (children precede parents)."""
    seen: set[int] = set()
    stack = [root]
    while stack:
        node = stack.pop()
        if node < 2 or node in seen:
            continue
        seen.add(node)
        _, low, high = nodes[node - 2]
        stack.append(low)
        stack.append(high)
    return sorted(seen)


def generate() -> str:
    data = _load()
    nodes = data["nodes"]
    functions = [(function["inputs"], function["root"]) for function in data["functions"]]
    bits = data["bits"]

    lines: list[str] = [
        '"""Monolith7 — compiled full-coverage decision model (analysis reference only).',
        "",
        "Mechanically generated by ``tools/compile_monolith7.py`` from the exact,",
        "exhaustively verified ``tools/monolith7_full_model.json`` decision model (see",
        "MONOLITH7_ANALYSIS.md). This is the same per-bit ROBDD formula as the",
        "interpreter in ``tools/monolith7_full_model.py``, unrolled into",
        "straight-line code — no new cryptanalysis. DO NOT EDIT — regenerate",
        "with ``python -m tools.compile_monolith7 --write``.",
        "",
        "**Not a runtime replacement.** Unlike the equivalent Monolith5 compile",
        "(``family0/monolith5_compact.py``), unrolling makes this about 20x",
        "*slower* and about 60x larger than generated code — see",
        "MODEL_BENCHMARKS.md. ``monolith_wrappers.py`` does not import this",
        "module; it is kept only as a benchmarked analysis reference documenting",
        "that negative result, alongside ``tools/monolith7_full_model.py``.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import struct",
        "from collections.abc import Sequence",
        "",
        "",
        "def execute_words(source: Sequence[int]) -> tuple[int, ...]:",
        '    """Map 24 source words to thirty-six destination words."""',
        "    if len(source) < 24:",
        '        raise ValueError("Monolith7 requires at least 24 source words")',
        "",
    ]

    seen_combo: dict[tuple[int, tuple[tuple[int, int], ...]], str] = {}
    bit_vars: list[str] = []
    for output_bit, (function_id, selectors) in enumerate(bits):
        combo = (function_id, tuple(map(tuple, selectors)))
        if combo in seen_combo:
            bit_vars.append(seen_combo[combo])
            continue

        _inputs, root = functions[function_id]
        prefix = f"b{output_bit}"

        def ref(node: int, prefix: str = prefix) -> str:
            return str(node) if node < 2 else f"{prefix}_n{node}"

        for node_id in _reachable(nodes, root):
            variable, low, high = nodes[node_id - 2]
            word, bit = selectors[variable]
            selector_expr = f"((source[{word}] >> {bit}) & 1)"
            low_ref, high_ref = ref(low), ref(high)
            lines.append(f"    {prefix}_n{node_id} = {low_ref} ^ (({high_ref} ^ {low_ref}) & {selector_expr})")

        root_ref = ref(root)
        if root >= 2:
            bit_vars.append(root_ref)
        else:
            # Whole-function constant: no node was emitted, use the literal directly.
            bit_vars.append(root_ref)
        seen_combo[combo] = bit_vars[-1]

    lines.append("")
    for word in range(36):
        word_bits = bit_vars[word * 32 : (word + 1) * 32]
        terms = [word_bits[0]] + [f"({term} << {position})" for position, term in enumerate(word_bits[1:], start=1)]
        lines.append(f"    w{word} = {' | '.join(terms)}")

    lines.append("")
    lines.append("    return (" + ", ".join(f"w{word}" for word in range(36)) + ")")
    lines.append("")
    lines.append("")
    lines.append("def execute(destination: bytearray, source: bytes) -> None:")
    lines.append('    """Write the thirty-six Monolith7 output words into destination[:144].')
    lines.append("")
    lines.append("    Signature matches the retired ``_generated/monolith7.py`` entry point.")
    lines.append('    """')
    lines.append('    words = struct.unpack("<24I", bytes(source[:96]))')
    lines.append('    destination[:144] = struct.pack("<36I", *execute_words(words))')
    lines.append("")
    return "\n".join(lines)


_TARGET = _HERE / "monolith7_compiled_model.py"


def compile_source() -> str:
    """Generate and ruff-format the compiled Monolith7 analysis module source."""
    return _ruff_format(generate())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify monolith7_compact.py is up to date, without writing.")
    parser.add_argument("--write", action="store_true", help="Write the generated source to monolith7_compact.py.")
    args = parser.parse_args(argv)

    source = compile_source()
    if args.check:
        if not _TARGET.is_file() or _TARGET.read_text(encoding="utf-8") != source:
            print(f"{_TARGET} is out of date; regenerate with python -m tools.compile_monolith7 --write", file=sys.stderr)
            return 1
        print(f"{_TARGET.name} matches the source model")
        return 0
    if args.write:
        _TARGET.write_text(source, encoding="utf-8")
        print(f"wrote {_TARGET}")
        return 0
    sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
